//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Prepayment part: fee itself, reimbursement, discount, VAT or rounding compensation.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ChargebacksPendingSubTotalPrepaymentPartType1 : IEquatable<ChargebacksPendingSubTotalPrepaymentPartType1>
    {
        public static readonly ChargebacksPendingSubTotalPrepaymentPartType1 Fee = new ChargebacksPendingSubTotalPrepaymentPartType1("fee");
        public static readonly ChargebacksPendingSubTotalPrepaymentPartType1 FeeReimbursement = new ChargebacksPendingSubTotalPrepaymentPartType1("fee-reimbursement");
        public static readonly ChargebacksPendingSubTotalPrepaymentPartType1 FeeDiscount = new ChargebacksPendingSubTotalPrepaymentPartType1("fee-discount");
        public static readonly ChargebacksPendingSubTotalPrepaymentPartType1 FeeVat = new ChargebacksPendingSubTotalPrepaymentPartType1("fee-vat");
        public static readonly ChargebacksPendingSubTotalPrepaymentPartType1 FeeRoundingCompensation = new ChargebacksPendingSubTotalPrepaymentPartType1("fee-rounding-compensation");

        private static readonly Dictionary <string, ChargebacksPendingSubTotalPrepaymentPartType1> _knownValues =
            new Dictionary <string, ChargebacksPendingSubTotalPrepaymentPartType1> ()
            {
                ["fee"] = Fee,
                ["fee-reimbursement"] = FeeReimbursement,
                ["fee-discount"] = FeeDiscount,
                ["fee-vat"] = FeeVat,
                ["fee-rounding-compensation"] = FeeRoundingCompensation
            };

        private static readonly ConcurrentDictionary<string, ChargebacksPendingSubTotalPrepaymentPartType1> _values =
            new ConcurrentDictionary<string, ChargebacksPendingSubTotalPrepaymentPartType1>(_knownValues);

        private ChargebacksPendingSubTotalPrepaymentPartType1(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ChargebacksPendingSubTotalPrepaymentPartType1 Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ChargebacksPendingSubTotalPrepaymentPartType1(value));
        }

        public static implicit operator ChargebacksPendingSubTotalPrepaymentPartType1(string value) => Of(value);
        public static implicit operator string(ChargebacksPendingSubTotalPrepaymentPartType1 chargebackspendingsubtotalprepaymentparttype1) => chargebackspendingsubtotalprepaymentparttype1.Value;

        public static ChargebacksPendingSubTotalPrepaymentPartType1[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ChargebacksPendingSubTotalPrepaymentPartType1);

        public bool Equals(ChargebacksPendingSubTotalPrepaymentPartType1? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}