//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: ab3ab76df2a1
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Models.Components;
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class ClientEmbedded
    {
        [JsonProperty("organization")]
        public EntityOrganization? Organization { get; set; }

        [JsonProperty("onboarding")]
        public EntityOnboardingStatus? Onboarding { get; set; }

        [JsonProperty("capabilities")]
        public List<EntityCapability>? Capabilities { get; set; }
    }
}