//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// In case of payments transactions with card, the card issuer will be available
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class CorrectionsPendingSubTotalCardIssuer1 : IEquatable<CorrectionsPendingSubTotalCardIssuer1>
    {
        public static readonly CorrectionsPendingSubTotalCardIssuer1 Amex = new CorrectionsPendingSubTotalCardIssuer1("amex");
        public static readonly CorrectionsPendingSubTotalCardIssuer1 Maestro = new CorrectionsPendingSubTotalCardIssuer1("maestro");
        public static readonly CorrectionsPendingSubTotalCardIssuer1 CarteBancaire = new CorrectionsPendingSubTotalCardIssuer1("carte-bancaire");
        public static readonly CorrectionsPendingSubTotalCardIssuer1 Other = new CorrectionsPendingSubTotalCardIssuer1("other");

        private static readonly Dictionary <string, CorrectionsPendingSubTotalCardIssuer1> _knownValues =
            new Dictionary <string, CorrectionsPendingSubTotalCardIssuer1> ()
            {
                ["amex"] = Amex,
                ["maestro"] = Maestro,
                ["carte-bancaire"] = CarteBancaire,
                ["other"] = Other
            };

        private static readonly ConcurrentDictionary<string, CorrectionsPendingSubTotalCardIssuer1> _values =
            new ConcurrentDictionary<string, CorrectionsPendingSubTotalCardIssuer1>(_knownValues);

        private CorrectionsPendingSubTotalCardIssuer1(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static CorrectionsPendingSubTotalCardIssuer1 Of(string value)
        {
            return _values.GetOrAdd(value, _ => new CorrectionsPendingSubTotalCardIssuer1(value));
        }

        public static implicit operator CorrectionsPendingSubTotalCardIssuer1(string value) => Of(value);
        public static implicit operator string(CorrectionsPendingSubTotalCardIssuer1 correctionspendingsubtotalcardissuer1) => correctionspendingsubtotalcardissuer1.Value;

        public static CorrectionsPendingSubTotalCardIssuer1[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as CorrectionsPendingSubTotalCardIssuer1);

        public bool Equals(CorrectionsPendingSubTotalCardIssuer1? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}