//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The card type.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class CreateCustomerPaymentCardFunding : IEquatable<CreateCustomerPaymentCardFunding>
    {
        public static readonly CreateCustomerPaymentCardFunding Debit = new CreateCustomerPaymentCardFunding("debit");
        public static readonly CreateCustomerPaymentCardFunding Credit = new CreateCustomerPaymentCardFunding("credit");
        public static readonly CreateCustomerPaymentCardFunding Prepaid = new CreateCustomerPaymentCardFunding("prepaid");
        public static readonly CreateCustomerPaymentCardFunding DeferredDebit = new CreateCustomerPaymentCardFunding("deferred-debit");

        private static readonly Dictionary <string, CreateCustomerPaymentCardFunding> _knownValues =
            new Dictionary <string, CreateCustomerPaymentCardFunding> ()
            {
                ["debit"] = Debit,
                ["credit"] = Credit,
                ["prepaid"] = Prepaid,
                ["deferred-debit"] = DeferredDebit
            };

        private static readonly ConcurrentDictionary<string, CreateCustomerPaymentCardFunding> _values =
            new ConcurrentDictionary<string, CreateCustomerPaymentCardFunding>(_knownValues);

        private CreateCustomerPaymentCardFunding(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static CreateCustomerPaymentCardFunding Of(string value)
        {
            return _values.GetOrAdd(value, _ => new CreateCustomerPaymentCardFunding(value));
        }

        public static implicit operator CreateCustomerPaymentCardFunding(string value) => Of(value);
        public static implicit operator string(CreateCustomerPaymentCardFunding createcustomerpaymentcardfunding) => createcustomerpaymentcardfunding.Value;

        public static CreateCustomerPaymentCardFunding[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as CreateCustomerPaymentCardFunding);

        public bool Equals(CreateCustomerPaymentCardFunding? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}