//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The type of discount.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class CreateSalesInvoiceLineTypeResponse : IEquatable<CreateSalesInvoiceLineTypeResponse>
    {
        public static readonly CreateSalesInvoiceLineTypeResponse Amount = new CreateSalesInvoiceLineTypeResponse("amount");
        public static readonly CreateSalesInvoiceLineTypeResponse Percentage = new CreateSalesInvoiceLineTypeResponse("percentage");

        private static readonly Dictionary <string, CreateSalesInvoiceLineTypeResponse> _knownValues =
            new Dictionary <string, CreateSalesInvoiceLineTypeResponse> ()
            {
                ["amount"] = Amount,
                ["percentage"] = Percentage
            };

        private static readonly ConcurrentDictionary<string, CreateSalesInvoiceLineTypeResponse> _values =
            new ConcurrentDictionary<string, CreateSalesInvoiceLineTypeResponse>(_knownValues);

        private CreateSalesInvoiceLineTypeResponse(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static CreateSalesInvoiceLineTypeResponse Of(string value)
        {
            return _values.GetOrAdd(value, _ => new CreateSalesInvoiceLineTypeResponse(value));
        }

        public static implicit operator CreateSalesInvoiceLineTypeResponse(string value) => Of(value);
        public static implicit operator string(CreateSalesInvoiceLineTypeResponse createsalesinvoicelinetyperesponse) => createsalesinvoicelinetyperesponse.Value;

        public static CreateSalesInvoiceLineTypeResponse[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as CreateSalesInvoiceLineTypeResponse);

        public bool Equals(CreateSalesInvoiceLineTypeResponse? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}