//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The applicable card fee region.
    /// </summary>
    public enum CreatePaymentFeeRegion
    {
        [JsonProperty("american-express")]
        AmericanExpress,
        [JsonProperty("amex-intra-eea")]
        AmexIntraEea,
        [JsonProperty("carte-bancaire")]
        CarteBancaire,
        [JsonProperty("intra-eu")]
        IntraEu,
        [JsonProperty("intra-eu-corporate")]
        IntraEuCorporate,
        [JsonProperty("domestic")]
        Domestic,
        [JsonProperty("maestro")]
        Maestro,
        [JsonProperty("other")]
        Other,
        [JsonProperty("inter")]
        Inter,
        [JsonProperty("intra_eea")]
        IntraEea,
    }

    public static class CreatePaymentFeeRegionExtension
    {
        public static string Value(this CreatePaymentFeeRegion value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CreatePaymentFeeRegion ToEnum(this string value)
        {
            foreach(var field in typeof(CreatePaymentFeeRegion).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CreatePaymentFeeRegion)
                    {
                        return (CreatePaymentFeeRegion)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CreatePaymentFeeRegion");
        }
    }

}