//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The payment&apos;s status. Refer to the <a href="https://docs.mollie.com/docs/status-change#/">documentation regarding statuses</a> for more info about which<br/>
    /// 
    /// <remarks>
    /// statuses occur at what point.
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class CreatePaymentStatusEnum : IEquatable<CreatePaymentStatusEnum>
    {
        public static readonly CreatePaymentStatusEnum Open = new CreatePaymentStatusEnum("open");
        public static readonly CreatePaymentStatusEnum Pending = new CreatePaymentStatusEnum("pending");
        public static readonly CreatePaymentStatusEnum Authorized = new CreatePaymentStatusEnum("authorized");
        public static readonly CreatePaymentStatusEnum Paid = new CreatePaymentStatusEnum("paid");
        public static readonly CreatePaymentStatusEnum Canceled = new CreatePaymentStatusEnum("canceled");
        public static readonly CreatePaymentStatusEnum Expired = new CreatePaymentStatusEnum("expired");
        public static readonly CreatePaymentStatusEnum Failed = new CreatePaymentStatusEnum("failed");

        private static readonly Dictionary <string, CreatePaymentStatusEnum> _knownValues =
            new Dictionary <string, CreatePaymentStatusEnum> ()
            {
                ["open"] = Open,
                ["pending"] = Pending,
                ["authorized"] = Authorized,
                ["paid"] = Paid,
                ["canceled"] = Canceled,
                ["expired"] = Expired,
                ["failed"] = Failed
            };

        private static readonly ConcurrentDictionary<string, CreatePaymentStatusEnum> _values =
            new ConcurrentDictionary<string, CreatePaymentStatusEnum>(_knownValues);

        private CreatePaymentStatusEnum(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static CreatePaymentStatusEnum Of(string value)
        {
            return _values.GetOrAdd(value, _ => new CreatePaymentStatusEnum(value));
        }

        public static implicit operator CreatePaymentStatusEnum(string value) => Of(value);
        public static implicit operator string(CreatePaymentStatusEnum createpaymentstatusenum) => createpaymentstatusenum.Value;

        public static CreatePaymentStatusEnum[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as CreatePaymentStatusEnum);

        public bool Equals(CreatePaymentStatusEnum? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}