//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 2b2e1eae56c7
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Models.Components;
    using Mollie.Utils;

    public class CreatePayoutRequest
    {
        /// <summary>
        /// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query<br/>
        /// parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by<br/>
        /// setting the `testmode` query parameter to `true`.<br/>
        /// <br/>
        /// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=testmode")]
        public bool? Testmode { get; set; }

        /// <summary>
        /// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")]
        public string? IdempotencyKey { get; set; }

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public PayoutRequest PayoutRequest { get; set; } = default!;
    }
}