//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// In case of payments transactions with card, the card issuer will be available
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2 : IEquatable<FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2>
    {
        public static readonly FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2 Amex = new FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2("amex");
        public static readonly FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2 Maestro = new FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2("maestro");
        public static readonly FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2 CarteBancaire = new FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2("carte-bancaire");
        public static readonly FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2 Other = new FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2("other");

        private static readonly Dictionary <string, FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2> _knownValues =
            new Dictionary <string, FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2> ()
            {
                ["amex"] = Amex,
                ["maestro"] = Maestro,
                ["carte-bancaire"] = CarteBancaire,
                ["other"] = Other
            };

        private static readonly ConcurrentDictionary<string, FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2> _values =
            new ConcurrentDictionary<string, FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2>(_knownValues);

        private FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2 Of(string value)
        {
            return _values.GetOrAdd(value, _ => new FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2(value));
        }

        public static implicit operator FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2(string value) => Of(value);
        public static implicit operator string(FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2 feeprepaymentsimmediatelyavailablesubtotalcardissuer2) => feeprepaymentsimmediatelyavailablesubtotalcardissuer2.Value;

        public static FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2);

        public bool Equals(FeePrepaymentsImmediatelyAvailableSubtotalCardIssuer2? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}