//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Models.Requests;
    using Mollie.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// The balance object.
    /// </summary>
    public class GetBalanceResponseBody
    {

        /// <summary>
        /// Indicates the response contains a balance object. Will always contain the string `balance` for this endpoint.
        /// </summary>
        [JsonProperty("resource")]
        public string? Resource { get; set; } = "balance";

        /// <summary>
        /// The identifier uniquely referring to this balance.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Whether this entity was created in live mode or in test mode.
        /// </summary>
        [JsonProperty("mode")]
        public GetBalanceMode? Mode { get; set; }

        /// <summary>
        /// The entity&apos;s date and time of creation, in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO 8601</a> format.
        /// </summary>
        [JsonProperty("createdAt")]
        public string? CreatedAt { get; set; }

        /// <summary>
        /// The balance&apos;s ISO 4217 currency code.
        /// </summary>
        [JsonProperty("currency")]
        public GetBalanceCurrency? Currency { get; set; }

        /// <summary>
        /// The description or name of the balance. Can be used to denote the purpose of the balance.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// The status of the balance.
        /// </summary>
        [JsonProperty("status")]
        public GetBalanceStatus? Status { get; set; }

        /// <summary>
        /// The frequency with which the available amount on the balance will be settled to the configured transfer<br/>
        /// 
        /// <remarks>
        /// destination.<br/>
        /// <br/>
        /// Settlements created during weekends or on bank holidays will take place on the next business day.
        /// </remarks>
        /// </summary>
        [JsonProperty("transferFrequency")]
        public GetBalanceTransferFrequency? TransferFrequency { get; set; }

        /// <summary>
        /// The minimum amount configured for scheduled automatic settlements. As soon as the amount on the balance exceeds<br/>
        /// 
        /// <remarks>
        /// this threshold, the complete balance will be paid out to the transfer destination according to the configured<br/>
        /// frequency.
        /// </remarks>
        /// </summary>
        [JsonProperty("transferThreshold")]
        public GetBalanceTransferThreshold? TransferThreshold { get; set; }

        /// <summary>
        /// The transfer reference set to be included in all the transfers for this balance.
        /// </summary>
        [JsonProperty("transferReference")]
        public string? TransferReference { get; set; } = null;

        /// <summary>
        /// The destination where the available amount will be automatically transferred to according to the configured<br/>
        /// 
        /// <remarks>
        /// transfer frequency.
        /// </remarks>
        /// </summary>
        [JsonProperty("transferDestination")]
        public GetBalanceTransferDestination? TransferDestination { get; set; } = null;

        /// <summary>
        /// The amount directly available on the balance, e.g. `{&quot;currency&quot;:&quot;EUR&quot;, &quot;value&quot;:&quot;100.00&quot;}`.
        /// </summary>
        [JsonProperty("availableAmount")]
        public GetBalanceAvailableAmount? AvailableAmount { get; set; }

        /// <summary>
        /// The total amount that is queued to be transferred to your balance. For example, a credit card payment can take a<br/>
        /// 
        /// <remarks>
        /// few days to clear.
        /// </remarks>
        /// </summary>
        [JsonProperty("pendingAmount")]
        public GetBalancePendingAmount? PendingAmount { get; set; }

        /// <summary>
        /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
        /// </summary>
        [JsonProperty("_links")]
        public GetBalanceLinks? Links { get; set; }
    }
}