//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Models.Components;
    using Mollie.Utils;
    
    public class GetMethodRequest
    {

        /// <summary>
        /// Provide the ID of the item you want to perform this operation on.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Response language
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=locale")]
        public LocaleParameter? Locale { get; set; }

        /// <summary>
        /// If provided, the `minimumAmount` and `maximumAmount` will be converted<br/>
        /// 
        /// <remarks>
        /// to the given currency. An error is returned if the currency is not supported by the payment method.
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=currency")]
        public string? Currency { get; set; }

        /// <summary>
        /// The identifier referring to the <a href="get-profile">profile</a> you wish to<br/>
        /// 
        /// <remarks>
        /// retrieve the resources for.<br/>
        /// <br/>
        /// Most API credentials are linked to a single profile. In these cases the `profileId` can be omitted. For<br/>
        /// organization-level credentials such as OAuth access tokens however, the `profileId` parameter is required.
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=profileId")]
        public string? ProfileId { get; set; }

        /// <summary>
        /// This endpoint allows you to include additional information via the `include` query string parameter.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=include")]
        public string? Include { get; set; } = null;

        /// <summary>
        /// Set this parameter to `first` to only return the methods that<br/>
        /// 
        /// <remarks>
        /// can be used for the first payment of a recurring sequence.<br/>
        /// <br/>
        /// Set it to `recurring` to only return methods that can be used for recurring payments or subscriptions.
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=sequenceType")]
        public SequenceType? SequenceType { get; set; }

        /// <summary>
        /// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query<br/>
        /// 
        /// <remarks>
        /// parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by<br/>
        /// setting the `testmode` query parameter to `true`.<br/>
        /// <br/>
        /// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=testmode")]
        public bool? Testmode { get; set; } = null;

        /// <summary>
        /// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")]
        public string? IdempotencyKey { get; set; }
    }
}