//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 831b60815e44
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Models.Requests;
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class GetOpenSettlementPeriods
    {
        /// <summary>
        /// An array of cost objects, describing the fees withheld for each payment method during this period.
        /// </summary>
        [JsonProperty("costs")]
        public List<GetOpenSettlementCost>? Costs { get; set; }

        /// <summary>
        /// An array of revenue objects containing the total revenue for each payment method during this period.
        /// </summary>
        [JsonProperty("revenue")]
        public List<GetOpenSettlementRevenue>? Revenue { get; set; }

        [JsonProperty("invoiceId")]
        public string? InvoiceId { get; set; }

        /// <summary>
        /// The invoice reference, if the invoice has been created already.
        /// </summary>
        [JsonProperty("invoiceReference")]
        public string? InvoiceReference { get; set; } = null;
    }
}