//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The wallet used when creating the payment.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetPaymentWallet : IEquatable<GetPaymentWallet>
    {
        public static readonly GetPaymentWallet Applepay = new GetPaymentWallet("applepay");

        private static readonly Dictionary <string, GetPaymentWallet> _knownValues =
            new Dictionary <string, GetPaymentWallet> ()
            {
                ["applepay"] = Applepay
            };

        private static readonly ConcurrentDictionary<string, GetPaymentWallet> _values =
            new ConcurrentDictionary<string, GetPaymentWallet>(_knownValues);

        private GetPaymentWallet(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetPaymentWallet Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetPaymentWallet(value));
        }

        public static implicit operator GetPaymentWallet(string value) => Of(value);
        public static implicit operator string(GetPaymentWallet getpaymentwallet) => getpaymentwallet.Value;

        public static GetPaymentWallet[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetPaymentWallet);

        public bool Equals(GetPaymentWallet? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}