//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The profile status determines whether the profile is able to receive live payments.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// * `unverified`: The profile has not been verified yet and can only be used to create test payments.<br/>
    /// * `verified`: The profile has been verified and can be used to create live payments and test payments.<br/>
    /// * `blocked`: The profile is blocked and can no longer be used or changed.
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetProfileStatus : IEquatable<GetProfileStatus>
    {
        public static readonly GetProfileStatus Unverified = new GetProfileStatus("unverified");
        public static readonly GetProfileStatus Verified = new GetProfileStatus("verified");
        public static readonly GetProfileStatus Blocked = new GetProfileStatus("blocked");

        private static readonly Dictionary <string, GetProfileStatus> _knownValues =
            new Dictionary <string, GetProfileStatus> ()
            {
                ["unverified"] = Unverified,
                ["verified"] = Verified,
                ["blocked"] = Blocked
            };

        private static readonly ConcurrentDictionary<string, GetProfileStatus> _values =
            new ConcurrentDictionary<string, GetProfileStatus>(_knownValues);

        private GetProfileStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetProfileStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetProfileStatus(value));
        }

        public static implicit operator GetProfileStatus(string value) => Of(value);
        public static implicit operator string(GetProfileStatus getprofilestatus) => getprofilestatus.Value;

        public static GetProfileStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetProfileStatus);

        public bool Equals(GetProfileStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}