//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// Indicate if the funds should be captured immediately or if you want to <a href="https://docs.mollie.com/docs/place-a-hold-for-a-payment#/">place a hold</a> <br/>
    /// 
    /// <remarks>
    /// and capture at a later time.<br/>
    /// <br/>
    /// This field needs to be set to `manual` for method `riverty`.
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetPaymentLinkPaymentsCaptureMode : IEquatable<GetPaymentLinkPaymentsCaptureMode>
    {
        public static readonly GetPaymentLinkPaymentsCaptureMode Automatic = new GetPaymentLinkPaymentsCaptureMode("automatic");
        public static readonly GetPaymentLinkPaymentsCaptureMode Manual = new GetPaymentLinkPaymentsCaptureMode("manual");

        private static readonly Dictionary <string, GetPaymentLinkPaymentsCaptureMode> _knownValues =
            new Dictionary <string, GetPaymentLinkPaymentsCaptureMode> ()
            {
                ["automatic"] = Automatic,
                ["manual"] = Manual
            };

        private static readonly ConcurrentDictionary<string, GetPaymentLinkPaymentsCaptureMode> _values =
            new ConcurrentDictionary<string, GetPaymentLinkPaymentsCaptureMode>(_knownValues);

        private GetPaymentLinkPaymentsCaptureMode(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetPaymentLinkPaymentsCaptureMode Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetPaymentLinkPaymentsCaptureMode(value));
        }

        public static implicit operator GetPaymentLinkPaymentsCaptureMode(string value) => Of(value);
        public static implicit operator string(GetPaymentLinkPaymentsCaptureMode getpaymentlinkpaymentscapturemode) => getpaymentlinkpaymentscapturemode.Value;

        public static GetPaymentLinkPaymentsCaptureMode[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetPaymentLinkPaymentsCaptureMode);

        public bool Equals(GetPaymentLinkPaymentsCaptureMode? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}