//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The type of product purchased. For example, a physical or a digital product.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// The `tip` payment line type is not available when creating a payment.
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetPaymentLineType : IEquatable<GetPaymentLineType>
    {
        public static readonly GetPaymentLineType Physical = new GetPaymentLineType("physical");
        public static readonly GetPaymentLineType Digital = new GetPaymentLineType("digital");
        public static readonly GetPaymentLineType ShippingFee = new GetPaymentLineType("shipping_fee");
        public static readonly GetPaymentLineType Discount = new GetPaymentLineType("discount");
        public static readonly GetPaymentLineType StoreCredit = new GetPaymentLineType("store_credit");
        public static readonly GetPaymentLineType GiftCard = new GetPaymentLineType("gift_card");
        public static readonly GetPaymentLineType Surcharge = new GetPaymentLineType("surcharge");
        public static readonly GetPaymentLineType Tip = new GetPaymentLineType("tip");

        private static readonly Dictionary <string, GetPaymentLineType> _knownValues =
            new Dictionary <string, GetPaymentLineType> ()
            {
                ["physical"] = Physical,
                ["digital"] = Digital,
                ["shipping_fee"] = ShippingFee,
                ["discount"] = Discount,
                ["store_credit"] = StoreCredit,
                ["gift_card"] = GiftCard,
                ["surcharge"] = Surcharge,
                ["tip"] = Tip
            };

        private static readonly ConcurrentDictionary<string, GetPaymentLineType> _values =
            new ConcurrentDictionary<string, GetPaymentLineType>(_knownValues);

        private GetPaymentLineType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetPaymentLineType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetPaymentLineType(value));
        }

        public static implicit operator GetPaymentLineType(string value) => Of(value);
        public static implicit operator string(GetPaymentLineType getpaymentlinetype) => getpaymentlinetype.Value;

        public static GetPaymentLineType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetPaymentLineType);

        public bool Equals(GetPaymentLineType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}