//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The applicable card fee region.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetPaymentFeeRegion : IEquatable<GetPaymentFeeRegion>
    {
        public static readonly GetPaymentFeeRegion AmericanExpress = new GetPaymentFeeRegion("american-express");
        public static readonly GetPaymentFeeRegion AmexIntraEea = new GetPaymentFeeRegion("amex-intra-eea");
        public static readonly GetPaymentFeeRegion CarteBancaire = new GetPaymentFeeRegion("carte-bancaire");
        public static readonly GetPaymentFeeRegion IntraEu = new GetPaymentFeeRegion("intra-eu");
        public static readonly GetPaymentFeeRegion IntraEuCorporate = new GetPaymentFeeRegion("intra-eu-corporate");
        public static readonly GetPaymentFeeRegion Domestic = new GetPaymentFeeRegion("domestic");
        public static readonly GetPaymentFeeRegion Maestro = new GetPaymentFeeRegion("maestro");
        public static readonly GetPaymentFeeRegion Other = new GetPaymentFeeRegion("other");
        public static readonly GetPaymentFeeRegion Inter = new GetPaymentFeeRegion("inter");
        public static readonly GetPaymentFeeRegion IntraEea = new GetPaymentFeeRegion("intra_eea");

        private static readonly Dictionary <string, GetPaymentFeeRegion> _knownValues =
            new Dictionary <string, GetPaymentFeeRegion> ()
            {
                ["american-express"] = AmericanExpress,
                ["amex-intra-eea"] = AmexIntraEea,
                ["carte-bancaire"] = CarteBancaire,
                ["intra-eu"] = IntraEu,
                ["intra-eu-corporate"] = IntraEuCorporate,
                ["domestic"] = Domestic,
                ["maestro"] = Maestro,
                ["other"] = Other,
                ["inter"] = Inter,
                ["intra_eea"] = IntraEea
            };

        private static readonly ConcurrentDictionary<string, GetPaymentFeeRegion> _values =
            new ConcurrentDictionary<string, GetPaymentFeeRegion>(_knownValues);

        private GetPaymentFeeRegion(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetPaymentFeeRegion Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetPaymentFeeRegion(value));
        }

        public static implicit operator GetPaymentFeeRegion(string value) => Of(value);
        public static implicit operator string(GetPaymentFeeRegion getpaymentfeeregion) => getpaymentfeeregion.Value;

        public static GetPaymentFeeRegion[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetPaymentFeeRegion);

        public bool Equals(GetPaymentFeeRegion? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}