//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Specifies the reference type
    /// </summary>
    public enum GetRefundType
    {
        [JsonProperty("acquirer-reference")]
        AcquirerReference,
    }

    public static class GetRefundTypeExtension
    {
        public static string Value(this GetRefundType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetRefundType ToEnum(this string value)
        {
            foreach(var field in typeof(GetRefundType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetRefundType)
                    {
                        return (GetRefundType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetRefundType");
        }
    }

}