//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The locale for the recipient, to be used for translations in PDF generation and payment pages.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetSalesInvoiceLocale : IEquatable<GetSalesInvoiceLocale>
    {
        public static readonly GetSalesInvoiceLocale EnUS = new GetSalesInvoiceLocale("en_US");
        public static readonly GetSalesInvoiceLocale EnGB = new GetSalesInvoiceLocale("en_GB");
        public static readonly GetSalesInvoiceLocale Nlnl = new GetSalesInvoiceLocale("nl_NL");
        public static readonly GetSalesInvoiceLocale NlBE = new GetSalesInvoiceLocale("nl_BE");
        public static readonly GetSalesInvoiceLocale Dede = new GetSalesInvoiceLocale("de_DE");
        public static readonly GetSalesInvoiceLocale DeAT = new GetSalesInvoiceLocale("de_AT");
        public static readonly GetSalesInvoiceLocale DeCH = new GetSalesInvoiceLocale("de_CH");
        public static readonly GetSalesInvoiceLocale Frfr = new GetSalesInvoiceLocale("fr_FR");
        public static readonly GetSalesInvoiceLocale FrBE = new GetSalesInvoiceLocale("fr_BE");

        private static readonly Dictionary <string, GetSalesInvoiceLocale> _knownValues =
            new Dictionary <string, GetSalesInvoiceLocale> ()
            {
                ["en_US"] = EnUS,
                ["en_GB"] = EnGB,
                ["nl_NL"] = Nlnl,
                ["nl_BE"] = NlBE,
                ["de_DE"] = Dede,
                ["de_AT"] = DeAT,
                ["de_CH"] = DeCH,
                ["fr_FR"] = Frfr,
                ["fr_BE"] = FrBE
            };

        private static readonly ConcurrentDictionary<string, GetSalesInvoiceLocale> _values =
            new ConcurrentDictionary<string, GetSalesInvoiceLocale>(_knownValues);

        private GetSalesInvoiceLocale(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetSalesInvoiceLocale Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetSalesInvoiceLocale(value));
        }

        public static implicit operator GetSalesInvoiceLocale(string value) => Of(value);
        public static implicit operator string(GetSalesInvoiceLocale getsalesinvoicelocale) => getsalesinvoicelocale.Value;

        public static GetSalesInvoiceLocale[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetSalesInvoiceLocale);

        public bool Equals(GetSalesInvoiceLocale? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}