//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// Whether this entity was created in live mode or in test mode.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GetWebhookEventMode2 : IEquatable<GetWebhookEventMode2>
    {
        public static readonly GetWebhookEventMode2 Live = new GetWebhookEventMode2("live");
        public static readonly GetWebhookEventMode2 Test = new GetWebhookEventMode2("test");

        private static readonly Dictionary <string, GetWebhookEventMode2> _knownValues =
            new Dictionary <string, GetWebhookEventMode2> ()
            {
                ["live"] = Live,
                ["test"] = Test
            };

        private static readonly ConcurrentDictionary<string, GetWebhookEventMode2> _values =
            new ConcurrentDictionary<string, GetWebhookEventMode2>(_knownValues);

        private GetWebhookEventMode2(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GetWebhookEventMode2 Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GetWebhookEventMode2(value));
        }

        public static implicit operator GetWebhookEventMode2(string value) => Of(value);
        public static implicit operator string(GetWebhookEventMode2 getwebhookeventmode2) => getwebhookeventmode2.Value;

        public static GetWebhookEventMode2[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GetWebhookEventMode2);

        public bool Equals(GetWebhookEventMode2? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}