//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// A comma-separated list of the wallets you support in your checkout. Wallets often require wallet specific code<br/>
    /// 
    /// <remarks>
    /// to check if they are available on the shoppers device, hence the need to indicate your support.
    /// </remarks>
    /// </summary>
    public enum IncludeWallets
    {
        [JsonProperty("applepay")]
        Applepay,
    }

    public static class IncludeWalletsExtension
    {
        public static string Value(this IncludeWallets value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static IncludeWallets ToEnum(this string value)
        {
            foreach(var field in typeof(IncludeWallets).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is IncludeWallets)
                    {
                        return (IncludeWallets)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum IncludeWallets");
        }
    }

}