//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 01c97bf3d589
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Models.Components;
    using Mollie.Models.Requests;
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Threading.Tasks;

    public class ListSalesInvoicesResponse
    {
        public Func<Task<ListSalesInvoicesResponse?>>? Next {get;set;}
        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// A list of sales invoice objects. For a complete reference of the sales invoice object, refer to the<br/>
        /// <a href="get-sales-invoice">Get sales invoice endpoint</a> documentation.
        /// </summary>
        public ListSalesInvoicesResponseBody? Object { get; set; }
    }
}