//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Models.Requests;
    using Mollie.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class ListSubscriptionsMetadataUnionType
    {
        private ListSubscriptionsMetadataUnionType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ListSubscriptionsMetadataUnionType Str { get { return new ListSubscriptionsMetadataUnionType("str"); } }
        
        public static ListSubscriptionsMetadataUnionType ListSubscriptionsMetadata { get { return new ListSubscriptionsMetadataUnionType("list_subscriptions_metadata"); } }
        
        public static ListSubscriptionsMetadataUnionType ArrayOfStr { get { return new ListSubscriptionsMetadataUnionType("arrayOfStr"); } }
        
        public static ListSubscriptionsMetadataUnionType Null { get { return new ListSubscriptionsMetadataUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ListSubscriptionsMetadataUnionType v) { return v.Value; }
        public static ListSubscriptionsMetadataUnionType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "list_subscriptions_metadata": return ListSubscriptionsMetadata;
                case "arrayOfStr": return ArrayOfStr;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ListSubscriptionsMetadataUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ListSubscriptionsMetadataUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Provide any data you like, for example a string or a JSON object. We will save the data alongside the entity. Whenever you fetch the entity with our API, we will also include the metadata. You can use up to approximately 1kB.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// Any metadata added to the subscription will be automatically forwarded to the payments generated for it.
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(ListSubscriptionsMetadataUnion.ListSubscriptionsMetadataUnionConverter))]
    public class ListSubscriptionsMetadataUnion {
        public ListSubscriptionsMetadataUnion(ListSubscriptionsMetadataUnionType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ListSubscriptionsMetadata? ListSubscriptionsMetadata { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<string>? ArrayOfStr { get; set; }

        public ListSubscriptionsMetadataUnionType Type { get; set; }


        public static ListSubscriptionsMetadataUnion CreateStr(string str) {
            ListSubscriptionsMetadataUnionType typ = ListSubscriptionsMetadataUnionType.Str;

            ListSubscriptionsMetadataUnion res = new ListSubscriptionsMetadataUnion(typ);
            res.Str = str;
            return res;
        }

        public static ListSubscriptionsMetadataUnion CreateListSubscriptionsMetadata(ListSubscriptionsMetadata listSubscriptionsMetadata) {
            ListSubscriptionsMetadataUnionType typ = ListSubscriptionsMetadataUnionType.ListSubscriptionsMetadata;

            ListSubscriptionsMetadataUnion res = new ListSubscriptionsMetadataUnion(typ);
            res.ListSubscriptionsMetadata = listSubscriptionsMetadata;
            return res;
        }

        public static ListSubscriptionsMetadataUnion CreateArrayOfStr(List<string> arrayOfStr) {
            ListSubscriptionsMetadataUnionType typ = ListSubscriptionsMetadataUnionType.ArrayOfStr;

            ListSubscriptionsMetadataUnion res = new ListSubscriptionsMetadataUnion(typ);
            res.ArrayOfStr = arrayOfStr;
            return res;
        }

        public static ListSubscriptionsMetadataUnion CreateNull() {
            ListSubscriptionsMetadataUnionType typ = ListSubscriptionsMetadataUnionType.Null;
            return new ListSubscriptionsMetadataUnion(typ);
        }

        public class ListSubscriptionsMetadataUnionConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(ListSubscriptionsMetadataUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ListSubscriptionsMetadataUnion(ListSubscriptionsMetadataUnionType.ListSubscriptionsMetadata)
                    {
                        ListSubscriptionsMetadata = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ListSubscriptionsMetadata>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ListSubscriptionsMetadata), new ListSubscriptionsMetadataUnion(ListSubscriptionsMetadataUnionType.ListSubscriptionsMetadata), "ListSubscriptionsMetadata"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new ListSubscriptionsMetadataUnion(ListSubscriptionsMetadataUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    return new ListSubscriptionsMetadataUnion(ListSubscriptionsMetadataUnionType.ArrayOfStr)
                    {
                        ArrayOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<string>), new ListSubscriptionsMetadataUnion(ListSubscriptionsMetadataUnionType.ArrayOfStr), "ArrayOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                ListSubscriptionsMetadataUnion res = (ListSubscriptionsMetadataUnion)value;
                if (ListSubscriptionsMetadataUnionType.FromString(res.Type).Equals(ListSubscriptionsMetadataUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.ListSubscriptionsMetadata != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ListSubscriptionsMetadata));
                    return;
                }
                if (res.ArrayOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfStr));
                    return;
                }

            }

        }

    }
}