//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The current status of the organization&apos;s onboarding process.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// * `needs-data` — The merchant needs to provide additional information<br/>
    /// * `in-review` — The merchant provided all information, awaiting review from Mollie<br/>
    /// * `completed` — The onboarding is completed
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ListClientsOnboardingStatus : IEquatable<ListClientsOnboardingStatus>
    {
        public static readonly ListClientsOnboardingStatus NeedsData = new ListClientsOnboardingStatus("needs-data");
        public static readonly ListClientsOnboardingStatus InReview = new ListClientsOnboardingStatus("in-review");
        public static readonly ListClientsOnboardingStatus Completed = new ListClientsOnboardingStatus("completed");

        private static readonly Dictionary <string, ListClientsOnboardingStatus> _knownValues =
            new Dictionary <string, ListClientsOnboardingStatus> ()
            {
                ["needs-data"] = NeedsData,
                ["in-review"] = InReview,
                ["completed"] = Completed
            };

        private static readonly ConcurrentDictionary<string, ListClientsOnboardingStatus> _values =
            new ConcurrentDictionary<string, ListClientsOnboardingStatus>(_knownValues);

        private ListClientsOnboardingStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ListClientsOnboardingStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ListClientsOnboardingStatus(value));
        }

        public static implicit operator ListClientsOnboardingStatus(string value) => Of(value);
        public static implicit operator string(ListClientsOnboardingStatus listclientsonboardingstatus) => listclientsonboardingstatus.Value;

        public static ListClientsOnboardingStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ListClientsOnboardingStatus);

        public bool Equals(ListClientsOnboardingStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}