//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Models.Requests;
    using Mollie.Utils;
    using Newtonsoft.Json;
    
    public class ListSettlementPaymentsRouting
    {

        /// <summary>
        /// Indicates the response contains a route object. Will always contain the string `route` for this endpoint.
        /// </summary>
        [JsonProperty("resource")]
        public string Resource { get; set; } = default!;

        /// <summary>
        /// The identifier uniquely referring to this route. Mollie will always refer to the route by this ID. Example: `rt_5B8cwPMGnU6qLbRvo7qEZo`.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Whether this entity was created in live mode or in test mode.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// Possible values: `live` `test`
        /// </remarks>
        /// </summary>
        [JsonProperty("mode")]
        public string Mode { get; set; } = default!;

        /// <summary>
        /// The portion of the total payment amount being routed. Currently only `EUR` payments can be routed.
        /// </summary>
        [JsonProperty("amount")]
        public ListSettlementPaymentsRoutingAmount Amount { get; set; } = default!;

        /// <summary>
        /// The destination of this portion of the payment.
        /// </summary>
        [JsonProperty("destination")]
        public ListSettlementPaymentsDestination Destination { get; set; } = default!;

        /// <summary>
        /// The date and time when the route was created. The date is given in ISO 8601 format.
        /// </summary>
        [JsonProperty("createdAt")]
        public string CreatedAt { get; set; } = default!;

        /// <summary>
        /// Optionally, schedule this portion of the payment to be transferred to its destination on a later date. The date must be given in `YYYY-MM-DD` format.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// If no date is given, the funds become available to the connected merchant as soon as the payment succeeds.
        /// </remarks>
        /// </summary>
        [JsonProperty("releaseDate")]
        public string? ReleaseDate { get; set; } = null;

        /// <summary>
        /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
        /// </summary>
        [JsonProperty("_links")]
        public ListSettlementPaymentsRoutingLinks Links { get; set; } = default!;
    }
}