//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// Indicates to what extent the payment is eligible for PayPal&apos;s Seller Protection. Only available for PayPal<br/>
    /// 
    /// <remarks>
    /// payments, and if the information is made available by PayPal.
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ListCustomerPaymentsSellerProtection : IEquatable<ListCustomerPaymentsSellerProtection>
    {
        public static readonly ListCustomerPaymentsSellerProtection Eligible = new ListCustomerPaymentsSellerProtection("Eligible");
        public static readonly ListCustomerPaymentsSellerProtection Ineligible = new ListCustomerPaymentsSellerProtection("Ineligible");
        public static readonly ListCustomerPaymentsSellerProtection PartiallyEligibleINROnly = new ListCustomerPaymentsSellerProtection("Partially Eligible - INR Only");
        public static readonly ListCustomerPaymentsSellerProtection PartiallyEligibleUnauthOnly = new ListCustomerPaymentsSellerProtection("Partially Eligible - Unauth Only");
        public static readonly ListCustomerPaymentsSellerProtection PartiallyEligible = new ListCustomerPaymentsSellerProtection("Partially Eligible");
        public static readonly ListCustomerPaymentsSellerProtection None = new ListCustomerPaymentsSellerProtection("None");
        public static readonly ListCustomerPaymentsSellerProtection Active = new ListCustomerPaymentsSellerProtection("Active");
        public static readonly ListCustomerPaymentsSellerProtection FraudControlUnauthPremiumEligible = new ListCustomerPaymentsSellerProtection("Fraud Control - Unauth Premium Eligible");

        private static readonly Dictionary <string, ListCustomerPaymentsSellerProtection> _knownValues =
            new Dictionary <string, ListCustomerPaymentsSellerProtection> ()
            {
                ["Eligible"] = Eligible,
                ["Ineligible"] = Ineligible,
                ["Partially Eligible - INR Only"] = PartiallyEligibleINROnly,
                ["Partially Eligible - Unauth Only"] = PartiallyEligibleUnauthOnly,
                ["Partially Eligible"] = PartiallyEligible,
                ["None"] = None,
                ["Active"] = Active,
                ["Fraud Control - Unauth Premium Eligible"] = FraudControlUnauthPremiumEligible
            };

        private static readonly ConcurrentDictionary<string, ListCustomerPaymentsSellerProtection> _values =
            new ConcurrentDictionary<string, ListCustomerPaymentsSellerProtection>(_knownValues);

        private ListCustomerPaymentsSellerProtection(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ListCustomerPaymentsSellerProtection Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ListCustomerPaymentsSellerProtection(value));
        }

        public static implicit operator ListCustomerPaymentsSellerProtection(string value) => Of(value);
        public static implicit operator string(ListCustomerPaymentsSellerProtection listcustomerpaymentssellerprotection) => listcustomerpaymentssellerprotection.Value;

        public static ListCustomerPaymentsSellerProtection[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ListCustomerPaymentsSellerProtection);

        public bool Equals(ListCustomerPaymentsSellerProtection? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}