//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The method by which the card was read by the terminal.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ListCustomerPaymentsCardReadMethod : IEquatable<ListCustomerPaymentsCardReadMethod>
    {
        public static readonly ListCustomerPaymentsCardReadMethod Chip = new ListCustomerPaymentsCardReadMethod("chip");
        public static readonly ListCustomerPaymentsCardReadMethod MagneticStripe = new ListCustomerPaymentsCardReadMethod("magnetic-stripe");
        public static readonly ListCustomerPaymentsCardReadMethod NearFieldCommunication = new ListCustomerPaymentsCardReadMethod("near-field-communication");
        public static readonly ListCustomerPaymentsCardReadMethod Contactless = new ListCustomerPaymentsCardReadMethod("contactless");
        public static readonly ListCustomerPaymentsCardReadMethod Moto = new ListCustomerPaymentsCardReadMethod("moto");

        private static readonly Dictionary <string, ListCustomerPaymentsCardReadMethod> _knownValues =
            new Dictionary <string, ListCustomerPaymentsCardReadMethod> ()
            {
                ["chip"] = Chip,
                ["magnetic-stripe"] = MagneticStripe,
                ["near-field-communication"] = NearFieldCommunication,
                ["contactless"] = Contactless,
                ["moto"] = Moto
            };

        private static readonly ConcurrentDictionary<string, ListCustomerPaymentsCardReadMethod> _values =
            new ConcurrentDictionary<string, ListCustomerPaymentsCardReadMethod>(_knownValues);

        private ListCustomerPaymentsCardReadMethod(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ListCustomerPaymentsCardReadMethod Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ListCustomerPaymentsCardReadMethod(value));
        }

        public static implicit operator ListCustomerPaymentsCardReadMethod(string value) => Of(value);
        public static implicit operator string(ListCustomerPaymentsCardReadMethod listcustomerpaymentscardreadmethod) => listcustomerpaymentscardreadmethod.Value;

        public static ListCustomerPaymentsCardReadMethod[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ListCustomerPaymentsCardReadMethod);

        public bool Equals(ListCustomerPaymentsCardReadMethod? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}