//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The type of destination. Currently only the destination type `organization` is supported.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ListCustomerPaymentsDestinationType : IEquatable<ListCustomerPaymentsDestinationType>
    {
        public static readonly ListCustomerPaymentsDestinationType Organization = new ListCustomerPaymentsDestinationType("organization");

        private static readonly Dictionary <string, ListCustomerPaymentsDestinationType> _knownValues =
            new Dictionary <string, ListCustomerPaymentsDestinationType> ()
            {
                ["organization"] = Organization
            };

        private static readonly ConcurrentDictionary<string, ListCustomerPaymentsDestinationType> _values =
            new ConcurrentDictionary<string, ListCustomerPaymentsDestinationType>(_knownValues);

        private ListCustomerPaymentsDestinationType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ListCustomerPaymentsDestinationType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ListCustomerPaymentsDestinationType(value));
        }

        public static implicit operator ListCustomerPaymentsDestinationType(string value) => Of(value);
        public static implicit operator string(ListCustomerPaymentsDestinationType listcustomerpaymentsdestinationtype) => listcustomerpaymentsdestinationtype.Value;

        public static ListCustomerPaymentsDestinationType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ListCustomerPaymentsDestinationType);

        public bool Equals(ListCustomerPaymentsDestinationType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}