//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Payment method of the mandate.<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// SEPA Direct Debit and PayPal mandates can be created directly.
    /// </remarks>
    /// </summary>
    public enum ListMandatesMethod
    {
        [JsonProperty("creditcard")]
        Creditcard,
        [JsonProperty("directdebit")]
        Directdebit,
        [JsonProperty("paypal")]
        Paypal,
    }

    public static class ListMandatesMethodExtension
    {
        public static string Value(this ListMandatesMethod value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ListMandatesMethod ToEnum(this string value)
        {
            foreach(var field in typeof(ListMandatesMethod).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ListMandatesMethod)
                    {
                        return (ListMandatesMethod)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ListMandatesMethod");
        }
    }

}