//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Present when the transaction represents a fee.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class RefundsMovedToAvailableSubTotalFeeType1 : IEquatable<RefundsMovedToAvailableSubTotalFeeType1>
    {
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 PaymentFee = new RefundsMovedToAvailableSubTotalFeeType1("payment-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 DirectDebitFailureFee = new RefundsMovedToAvailableSubTotalFeeType1("direct-debit-failure-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 UnauthorizedDirectDebitFee = new RefundsMovedToAvailableSubTotalFeeType1("unauthorized-direct-debit-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 BankChargedDirectDebitFailureFee = new RefundsMovedToAvailableSubTotalFeeType1("bank-charged-direct-debit-failure-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 PartnerCommission = new RefundsMovedToAvailableSubTotalFeeType1("partner-commission");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 ApplicationFee = new RefundsMovedToAvailableSubTotalFeeType1("application-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 CaptureFee = new RefundsMovedToAvailableSubTotalFeeType1("capture-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 RefundFee = new RefundsMovedToAvailableSubTotalFeeType1("refund-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 ChargebackFee = new RefundsMovedToAvailableSubTotalFeeType1("chargeback-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 PaymentNotificationFee = new RefundsMovedToAvailableSubTotalFeeType1("payment-notification-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 TransferNotificationFee = new RefundsMovedToAvailableSubTotalFeeType1("transfer-notification-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 PayoutFee = new RefundsMovedToAvailableSubTotalFeeType1("payout-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 FeeDiscount = new RefundsMovedToAvailableSubTotalFeeType1("fee-discount");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 FeeReimbursement = new RefundsMovedToAvailableSubTotalFeeType1("fee-reimbursement");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 PlatformVolumeFee = new RefundsMovedToAvailableSubTotalFeeType1("platform-volume-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 PlatformConnectedOrganizationsFee = new RefundsMovedToAvailableSubTotalFeeType1("platform-connected-organizations-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 BalanceChargeFee = new RefundsMovedToAvailableSubTotalFeeType1("balance-charge-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 ThreedsAuthenticationAttemptFee = new RefundsMovedToAvailableSubTotalFeeType1("3ds-authentication-attempt-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 TerminalMonthlyFee = new RefundsMovedToAvailableSubTotalFeeType1("terminal-monthly-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 AcceptanceRiskFee = new RefundsMovedToAvailableSubTotalFeeType1("acceptance-risk-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 TopUpFee = new RefundsMovedToAvailableSubTotalFeeType1("top-up-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 PaymentGatewayFee = new RefundsMovedToAvailableSubTotalFeeType1("payment-gateway-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 MastercardSpecialtyMerchantProgramProcessingFee = new RefundsMovedToAvailableSubTotalFeeType1("mastercard-specialty-merchant-program-processing-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 MastercardSpecialtyMerchantProgramRegistrationFee = new RefundsMovedToAvailableSubTotalFeeType1("mastercard-specialty-merchant-program-registration-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 VisaIntegrityRiskProgramProcessingFee = new RefundsMovedToAvailableSubTotalFeeType1("visa-integrity-risk-program-processing-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 VisaIntegrityRiskProgramRegistrationFee = new RefundsMovedToAvailableSubTotalFeeType1("visa-integrity-risk-program-registration-fee");
        public static readonly RefundsMovedToAvailableSubTotalFeeType1 MinimumInvoiceAmountFee = new RefundsMovedToAvailableSubTotalFeeType1("minimum-invoice-amount-fee");

        private static readonly Dictionary <string, RefundsMovedToAvailableSubTotalFeeType1> _knownValues =
            new Dictionary <string, RefundsMovedToAvailableSubTotalFeeType1> ()
            {
                ["payment-fee"] = PaymentFee,
                ["direct-debit-failure-fee"] = DirectDebitFailureFee,
                ["unauthorized-direct-debit-fee"] = UnauthorizedDirectDebitFee,
                ["bank-charged-direct-debit-failure-fee"] = BankChargedDirectDebitFailureFee,
                ["partner-commission"] = PartnerCommission,
                ["application-fee"] = ApplicationFee,
                ["capture-fee"] = CaptureFee,
                ["refund-fee"] = RefundFee,
                ["chargeback-fee"] = ChargebackFee,
                ["payment-notification-fee"] = PaymentNotificationFee,
                ["transfer-notification-fee"] = TransferNotificationFee,
                ["payout-fee"] = PayoutFee,
                ["fee-discount"] = FeeDiscount,
                ["fee-reimbursement"] = FeeReimbursement,
                ["platform-volume-fee"] = PlatformVolumeFee,
                ["platform-connected-organizations-fee"] = PlatformConnectedOrganizationsFee,
                ["balance-charge-fee"] = BalanceChargeFee,
                ["3ds-authentication-attempt-fee"] = ThreedsAuthenticationAttemptFee,
                ["terminal-monthly-fee"] = TerminalMonthlyFee,
                ["acceptance-risk-fee"] = AcceptanceRiskFee,
                ["top-up-fee"] = TopUpFee,
                ["payment-gateway-fee"] = PaymentGatewayFee,
                ["mastercard-specialty-merchant-program-processing-fee"] = MastercardSpecialtyMerchantProgramProcessingFee,
                ["mastercard-specialty-merchant-program-registration-fee"] = MastercardSpecialtyMerchantProgramRegistrationFee,
                ["visa-integrity-risk-program-processing-fee"] = VisaIntegrityRiskProgramProcessingFee,
                ["visa-integrity-risk-program-registration-fee"] = VisaIntegrityRiskProgramRegistrationFee,
                ["minimum-invoice-amount-fee"] = MinimumInvoiceAmountFee
            };

        private static readonly ConcurrentDictionary<string, RefundsMovedToAvailableSubTotalFeeType1> _values =
            new ConcurrentDictionary<string, RefundsMovedToAvailableSubTotalFeeType1>(_knownValues);

        private RefundsMovedToAvailableSubTotalFeeType1(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static RefundsMovedToAvailableSubTotalFeeType1 Of(string value)
        {
            return _values.GetOrAdd(value, _ => new RefundsMovedToAvailableSubTotalFeeType1(value));
        }

        public static implicit operator RefundsMovedToAvailableSubTotalFeeType1(string value) => Of(value);
        public static implicit operator string(RefundsMovedToAvailableSubTotalFeeType1 refundsmovedtoavailablesubtotalfeetype1) => refundsmovedtoavailablesubtotalfeetype1.Value;

        public static RefundsMovedToAvailableSubTotalFeeType1[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as RefundsMovedToAvailableSubTotalFeeType1);

        public bool Equals(RefundsMovedToAvailableSubTotalFeeType1? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}