//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: ad4c133ded63
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Models.Components;
    using Mollie.Utils;

    public class TerminalsListPairingCodesRequest
    {
        /// <summary>
        /// Provide an ID to start the result set from the item with the given ID and onwards. This allows you to paginate the<br/>
        /// result set.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=from")]
        public string? From { get; set; } = null;

        /// <summary>
        /// The maximum number of items to return. Defaults to 50 items.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = null;

        /// <summary>
        /// Used for setting the direction of the result set. Defaults to descending order, meaning the results are ordered from<br/>
        /// newest to oldest.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort")]
        public Sorting? Sort { get; set; }

        /// <summary>
        /// The identifier referring to the <a href="get-profile">profile</a> you wish to retrieve pairing codes for.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=profileId")]
        public string? ProfileId { get; set; }

        /// <summary>
        /// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")]
        public string? IdempotencyKey { get; set; }
    }
}