//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Requests
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The locale for the recipient, to be used for translations in PDF generation and payment pages.
    /// </summary>
    public enum UpdateSalesInvoiceLocaleRequest
    {
        [JsonProperty("en_US")]
        EnUS,
        [JsonProperty("en_GB")]
        EnGB,
        [JsonProperty("nl_NL")]
        Nlnl,
        [JsonProperty("nl_BE")]
        NlBE,
        [JsonProperty("de_DE")]
        Dede,
        [JsonProperty("de_AT")]
        DeAT,
        [JsonProperty("de_CH")]
        DeCH,
        [JsonProperty("fr_FR")]
        Frfr,
        [JsonProperty("fr_BE")]
        FrBE,
    }

    public static class UpdateSalesInvoiceLocaleRequestExtension
    {
        public static string Value(this UpdateSalesInvoiceLocaleRequest value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static UpdateSalesInvoiceLocaleRequest ToEnum(this string value)
        {
            foreach(var field in typeof(UpdateSalesInvoiceLocaleRequest).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is UpdateSalesInvoiceLocaleRequest)
                    {
                        return (UpdateSalesInvoiceLocaleRequest)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum UpdateSalesInvoiceLocaleRequest");
        }
    }

}