//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MollieApi.Models.Requests
{
    using MollieApi.Models.Requests;
    using MollieApi.Utils;
    using Newtonsoft.Json;
    
    public class BalanceTransaction
    {

        /// <summary>
        /// Indicates the response contains a balance transaction object. Will always contain the string `balance-transaction` for this endpoint.
        /// </summary>
        [JsonProperty("resource")]
        public string? Resource { get; set; } = "balance-transaction";

        /// <summary>
        /// The identifier uniquely referring to this balance transaction.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The type of transaction, for example `payment` or `refund`. Values include the below examples, although this list is not definitive.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// * Regular payment processing: `payment` `capture` `unauthorized-direct-debit` `failed-payment`<br/>
        /// * Refunds and chargebacks: `refund` `returned-refund` `chargeback` `chargeback-reversal`<br/>
        /// * Settlements: `outgoing-transfer` `canceled-outgoing-transfer` `returned-transfer`<br/>
        /// * Invoicing: `invoice-compensation` `balance-correction`<br/>
        /// * Mollie Connect: `application-fee` `split-payment` `platform-payment-refund` `platform-payment-chargeback`<br/>
        /// <br/>
        /// Possible values: `application-fee` `capture` `chargeback` `chargeback-reversal` `failed-payment-fee` `failed-payment` `invoice-compensation` `payment` `payment-fee` `payment-commission` `refund` `returned-refund` `returned-transfer` `split-payment` `outgoing-transfer` `capture-commission` `canceled-outgoing-transfer` `incoming-transfer` `api-payment-rolling-reserve-release` `capture-rolling-reserve-release` `reimbursement-fee` `balance-correction` `unauthorized-direct-debit` `bank-charged-failure-fee` `platform-payment-refund` `refund-compensation` `returned-refund-compensation` `returned-platform-payment-refund` `platform-payment-chargeback` `chargeback-compensation` `reversed-platform-payment-chargeback` `reversed-chargeback-compensation` `failed-split-payment-platform` `failed-split-payment-compensation` `cash-advance-loan` `platform-connected-organizations-fee` `split-transaction` `managed-fee` `returned-managed-fee` `topup` `balance-reserve` `balance-reserve-return` `movement` `post-payment-split-payment` `cash-collateral-issuance` `cash-collateral-release`
        /// </remarks>
        /// </summary>
        [JsonProperty("type")]
        public string? Type { get; set; }

        /// <summary>
        /// The final amount that was moved to or from the balance. If the transaction moves funds away from the balance, for example when it concerns a refund, the amount will be negative.
        /// </summary>
        [JsonProperty("resultAmount")]
        public ResultAmount? ResultAmount { get; set; }

        /// <summary>
        /// The amount that was to be moved to or from the balance, excluding deductions. If the transaction moves funds away from the balance, for example when it concerns a refund, the amount will be negative.
        /// </summary>
        [JsonProperty("initialAmount")]
        public InitialAmount? InitialAmount { get; set; }

        /// <summary>
        /// The total amount of deductions withheld from the movement. For example, if we charge a €0.29 fee on a €10 payment, the deductions amount will be `{&quot;currency&quot;:&quot;EUR&quot;, &quot;value&quot;:&quot;-0.29&quot;}`.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// When moving funds to a balance, we always round the deduction to a &apos;real&apos; amount. Any differences between these real-time rounded amounts and the final invoice will be compensated when the invoice is generated.
        /// </remarks>
        /// </summary>
        [JsonProperty("deductions")]
        public Deductions? Deductions { get; set; } = null;

        /// <summary>
        /// Depending on the type of the balance transaction, we will try to give more context about the specific event that triggered it. For example, the context object for a payment transaction will look like `{&quot;paymentId&quot;: &quot;tr_5B8cwPMGnU6qLbRvo7qEZo&quot;, &quot;paymentDescription&quot;: &quot;Description&quot;}`.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// Below is a complete list of the context values that each type of transaction will have.<br/>
        /// <br/>
        /// * Type `payment`: `paymentId`, `paymentDescription`<br/>
        /// * Type `capture`: `paymentId` `captureId`, `paymentDescription`, `captureDescription`<br/>
        /// * Type `capture-commission`: `paymentId`, `paymentDescription`, `organizationId`<br/>
        /// * Type `capture-rolling-reserve-release`: `paymentId`, `paymentDescription`, `captureId`, `captureDescription`<br/>
        /// * Type `unauthorized-direct-debit`: `paymentId`, `paymentDescription`<br/>
        /// * Type `failed-payment`: `paymentId`, `paymentDescription`<br/>
        /// * Type `refund`: `paymentId` `refundId`, `paymentDescription`, `refundDescription`<br/>
        /// * Type `refund-compensation`: `paymentId` `refundId`, `paymentDescription`, `refundDescription`<br/>
        /// * Type `returned-refund`: `paymentId` `refundId`, `paymentDescription`, `refundDescription`<br/>
        /// * Type `returned-refund-compensation`: `paymentId` `refundId`, `paymentDescription`, `refundDescription`<br/>
        /// * Type `chargeback`: `paymentId` `chargebackId`, `paymentDescription`, `chargebackDescription`<br/>
        /// * Type `chargeback-reversal`: `paymentId`, `chargebackId`, `paymentDescription`, `chargebackDescription`<br/>
        /// * Type `chargeback-compensation`: `paymentId`, `chargebackId`, `paymentDescription`, `chargebackDescription`<br/>
        /// * Type `reversed-chargeback-compensation`: `paymentId`, `chargebackId`, `paymentDescription`, `chargebackDescription`<br/>
        /// * Type `outgoing-transfer`: `settlementId` `transferId`<br/>
        /// * Type `canceled-outgoing-transfer`: `settlementId` `transferId`<br/>
        /// * Type `returned-transfer`: `settlementId` `transferId`<br/>
        /// * Type `invoice-compensation`: `invoiceId`<br/>
        /// * Type `balance-correction`: none<br/>
        /// * Type `application-fee`: `paymentId`, `paymentDescription`, `payingOwner`<br/>
        /// * Type `split-payment`: `paymentId`, `paymentDescription`, `paymentOwner`<br/>
        /// * Type `platform-payment-refund`: `paymentId` `refundId`, `paymentDescription`, `refundDescription`<br/>
        /// * Type `returned-platform-payment-refund`: `paymentId` `refundId`, `paymentDescription`, `refundDescription`<br/>
        /// * Type `platform-payment-chargeback`: `paymentId` `chargebackId`, `paymentDescription`, `chargebackDescription`<br/>
        /// * Type `reversed-platform-payment-chargeback`: `paymentId` `chargebackId`, `paymentDescription`, `chargebackDescription`<br/>
        /// * Type `payment-commission`: `paymentId`, `paymentDescription`, `organizationId`<br/>
        /// * Type `reimbursement-fee`: `paymentId`, `paymentDescription`<br/>
        /// * Type `failed-payment-fee`: `paymentId`, `paymentDescription`<br/>
        /// * Type `payment-fee`: `paymentId`, `paymentDescription`<br/>
        /// * Type `cash-advance-loan`: none<br/>
        /// * Type `platform-connected-organizations-fee`: none<br/>
        /// * Type `managed-fee`: `feeType`, `&lt;name of the fee&gt;Id`<br/>
        /// * Type `returned-managed-fee`:  `feeType`, `&lt;name of the fee&gt;Id`<br/>
        /// * Type `topup`: none<br/>
        /// * Type `balance-reserve`: none<br/>
        /// * Type `balance-reserve-return`: none<br/>
        /// * Type `movement`: none<br/>
        /// * Type `post-payment-split-payment`: `paymentId`<br/>
        /// * Type `cash-collateral-issuance`: none<br/>
        /// * Type `cash-collateral-release`: none
        /// </remarks>
        /// </summary>
        [JsonProperty("context")]
        public Context? Context { get; set; }

        /// <summary>
        /// The entity&apos;s date and time of creation, in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO 8601</a> format.
        /// </summary>
        [JsonProperty("createdAt")]
        public string? CreatedAt { get; set; }
    }
}