//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MollieApi.Models.Requests
{
    using MollieApi.Models.Components;
    using MollieApi.Models.Requests;
    using MollieApi.Utils;
    using Newtonsoft.Json;
    
    public class ListAllRefundsResponse
    {

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// A list of refund objects. For a complete reference of the refund object, refer to the <a href="get-refund">Get refund endpoint</a> documentation.
        /// </summary>
        public ListAllRefundsResponseBody? Object { get; set; }
    }
}