//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MollieApi.Models.Requests
{
    using MollieApi.Utils;
    using Newtonsoft.Json;
    
    public class ReleaseAuthorizationRequestBody
    {

        /// <summary>
        /// The identifier referring to the <a href="get-profile">profile</a> this entity belongs to.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// Most API credentials are linked to a single profile. In these cases the `profileId` can be omitted in the creation request. For organization-level credentials such as OAuth access tokens however, the `profileId` parameter is required.
        /// </remarks>
        /// </summary>
        [JsonProperty("profileId")]
        public string? ProfileId { get; set; }

        /// <summary>
        /// Whether to create the entity in test mode or live mode.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// Most API credentials are specifically created for either live mode or test mode, in which case this parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
        /// </remarks>
        /// </summary>
        [JsonProperty("testmode")]
        public bool? Testmode { get; set; } = null;
    }
}