//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 0e3261f67741
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie
{
    using Mollie.Hooks;
    using Mollie.Models.Components;
    using Mollie.Models.Errors;
    using Mollie.Models.Requests;
    using Mollie.Utils;
    using Mollie.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading;
    using System.Threading.Tasks;

    public interface IVerifyPayees
    {
        /// <summary>
        /// Verify Payee.
        /// </summary>
        /// <remarks>
        /// &gt; 🚧 Beta feature<br/>
        /// &gt;<br/>
        /// &gt; This feature is currently in beta testing, and the final specification may still change.<br/>
        /// <br/>
        /// Perform a Verification of Payee (VoP) check. This allows you to verify the account holder name against the<br/>
        /// records held by the receiving bank before initiating a transfer.<br/>
        /// <br/>
        /// The verification result indicates whether the provided name matches, closely matches, or does not match the<br/>
        /// name on file at the receiving bank. This helps prevent misdirected payments.<br/>
        /// <br/>
        /// ### Simulating verification scenarios in test mode<br/>
        /// <br/>
        /// In test mode, you can simulate various verification outcomes by adjusting the creditor name in the<br/>
        /// `creditorBankAccount.accountHolderName` property. This allows you to test all possible Verification of Payee<br/>
        /// results without needing special properties. The names are case insensitive.<br/>
        /// <br/>
        /// | Account holder name                    | Scenario                                      | Verification result | Suggested name |<br/>
        /// |----------------------------------------|-----------------------------------------------|---------------------|----------------|<br/>
        /// | `John Close Match`                     | Name closely matches the bank records          | `close-match`       | `John Match`   |<br/>
        /// | `John No Match`                        | Name does not match the bank records           | `no-match`          | —              |<br/>
        /// | `John Unavailable`                     | Verification is not available                  | `not-available`     | —              |<br/>
        /// | Any other name                         | Default: name matches the bank records         | `match`             | —              |<br/>
        /// <para>This operation requires <see cref="Mollie.Models.Components.Security.OrganizationAccessToken"/> to be set in the security parameter when initializing the SDK.</para>
        /// </remarks>
        /// <param name="idempotencyKey">A unique key to ensure idempotent requests. This key should be a UUID v4 string.</param>
        /// <param name="verificationOfPayeeRequest">A <see cref="VerificationOfPayeeRequest"/> parameter.</param>
        /// <param name="retryConfig">The retry configuration to use for this operation.</param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="VerifyPayeeResponse"/> response envelope when completed.</returns>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="ErrorResponse">
        /// The request contains issues. For example, if the creditor bank account&lt;br/&gt;<br/>
        /// details are missing or invalid. Thrown when the API returns a 422, 429 or 503 response.
        /// </exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<VerifyPayeeResponse> CreateAsync(
            string? idempotencyKey = null,
            VerificationOfPayeeRequest? verificationOfPayeeRequest = null,
            RetryConfig? retryConfig = null,
            CancellationToken? cancellationToken = null
        );
    }

    public class VerifyPayees: IVerifyPayees
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        public VerifyPayees(SDKConfig config)
        {
            SDKConfiguration = config;
        }

        /// <summary>
        /// Verify Payee.
        /// </summary>
        /// <remarks>
        /// &gt; 🚧 Beta feature<br/>
        /// &gt;<br/>
        /// &gt; This feature is currently in beta testing, and the final specification may still change.<br/>
        /// <br/>
        /// Perform a Verification of Payee (VoP) check. This allows you to verify the account holder name against the<br/>
        /// records held by the receiving bank before initiating a transfer.<br/>
        /// <br/>
        /// The verification result indicates whether the provided name matches, closely matches, or does not match the<br/>
        /// name on file at the receiving bank. This helps prevent misdirected payments.<br/>
        /// <br/>
        /// ### Simulating verification scenarios in test mode<br/>
        /// <br/>
        /// In test mode, you can simulate various verification outcomes by adjusting the creditor name in the<br/>
        /// `creditorBankAccount.accountHolderName` property. This allows you to test all possible Verification of Payee<br/>
        /// results without needing special properties. The names are case insensitive.<br/>
        /// <br/>
        /// | Account holder name                    | Scenario                                      | Verification result | Suggested name |<br/>
        /// |----------------------------------------|-----------------------------------------------|---------------------|----------------|<br/>
        /// | `John Close Match`                     | Name closely matches the bank records          | `close-match`       | `John Match`   |<br/>
        /// | `John No Match`                        | Name does not match the bank records           | `no-match`          | —              |<br/>
        /// | `John Unavailable`                     | Verification is not available                  | `not-available`     | —              |<br/>
        /// | Any other name                         | Default: name matches the bank records         | `match`             | —              |<br/>
        /// <para>This operation requires <see cref="Mollie.Models.Components.Security.OrganizationAccessToken"/> to be set in the security parameter when initializing the SDK.</para>
        /// </remarks>
        /// <param name="idempotencyKey">A unique key to ensure idempotent requests. This key should be a UUID v4 string.</param>
        /// <param name="verificationOfPayeeRequest">A <see cref="VerificationOfPayeeRequest"/> parameter.</param>
        /// <param name="retryConfig">The retry configuration to use for this operation.</param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="VerifyPayeeResponse"/> response envelope when completed.</returns>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="ErrorResponse">
        /// The request contains issues. For example, if the creditor bank account&lt;br/&gt;<br/>
        /// details are missing or invalid. Thrown when the API returns a 422, 429 or 503 response.
        /// </exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<VerifyPayeeResponse> CreateAsync(
            string? idempotencyKey = null,
            VerificationOfPayeeRequest? verificationOfPayeeRequest = null,
            RetryConfig? retryConfig = null,
            CancellationToken? cancellationToken = null
        )
        {
            var request = new VerifyPayeeRequest()
            {
                IdempotencyKey = idempotencyKey,
                VerificationOfPayeeRequest = verificationOfPayeeRequest,
            };

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = baseUrl + "/business-accounts/payee-verifications";

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/hal+json");
            }

            var serializedBody = RequestBodySerializer.Serialize(request, "VerificationOfPayeeRequest", "json", false, true);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource, new string[] { "OrganizationAccessToken" }).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "verify-payee", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            if (retryConfig == null)
            {
                if (this.SDKConfiguration.RetryConfig != null)
                {
                    retryConfig = this.SDKConfiguration.RetryConfig;
                }
                else
                {
                    var backoff = new BackoffStrategy(
                        initialIntervalMs: 500L,
                        maxIntervalMs: 5000L,
                        maxElapsedTimeMs: 7500L,
                        exponent: 2
                    );
                    retryConfig = new RetryConfig(
                        strategy: RetryConfig.RetryStrategy.BACKOFF,
                        backoff: backoff,
                        retryConnectionErrors: true
                    );
                }
            }

            List<string> statusCodes = new List<string>
            {
                "5xx",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Mollie.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/hal+json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    VerificationOfPayeeResponse obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<VerificationOfPayeeResponse>(httpResponseBody, NullValueHandling.Include);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into VerificationOfPayeeResponse.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new VerifyPayeeResponse()
                    {
                        HttpMeta = new Models.Components.HTTPMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.VerificationOfPayeeResponse = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{422, 429}.Contains(responseStatusCode))
            {
                if(Utilities.IsContentTypeMatch("application/hal+json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorResponsePayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorResponsePayload>(httpResponseBody, NullValueHandling.Include);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorResponsePayload.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    payload.HttpMeta = new Models.Components.HTTPMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    };

                    throw new ErrorResponse(payload, httpRequest, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 503)
            {
                if(Utilities.IsContentTypeMatch("application/hal+json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ErrorResponsePayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ErrorResponsePayload>(httpResponseBody, NullValueHandling.Include);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ErrorResponsePayload.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    payload.HttpMeta = new Models.Components.HTTPMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    };

                    throw new ErrorResponse(payload, httpRequest, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }

    }
}