//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 7bab14e318f3
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Models.Components;
    using Mollie.Utils;
    using Newtonsoft.Json;
    using NodaTime;

    public class CreateDraftTransferRequest
    {
        /// <summary>
        /// The IBAN of the debtor's (sender) Mollie Business Account. Defaults to your organization's primary account<br/>
        /// if omitted.
        /// </summary>
        [JsonProperty("debtorIban")]
        public string? DebtorIban { get; set; }

        /// <summary>
        /// A party involved in the draft transfer, representing either the debtor (sender) or creditor<br/>
        /// (recipient). Contains the party's name and account details.
        /// </summary>
        [JsonProperty("creditor")]
        public DraftTransferParty Creditor { get; set; } = default!;

        /// <summary>
        /// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
        /// </summary>
        [JsonProperty("amount")]
        public Amount Amount { get; set; } = default!;

        /// <summary>
        /// A short description of the draft transfer. Once approved, this will appear on the bank statement of both<br/>
        /// the debtor and creditor.
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Include)]
        public string? Description { get; set; }

        /// <summary>
        /// The date on which the resulting transfer will be executed, once approved. Defaults to same-day if omitted,<br/>
        /// in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO 8601</a> date format.
        /// </summary>
        [JsonProperty("scheduledExecutionDate")]
        public LocalDate? ScheduledExecutionDate { get; set; } = null;

        /// <summary>
        /// Whether to create the entity in test mode or live mode.<br/>
        /// <br/>
        /// Most API credentials are specifically created for either live mode or test mode, in which case this parameter must<br/>
        /// not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting<br/>
        /// `testmode` to `true`.
        /// </summary>
        [JsonProperty("testmode")]
        public bool? Testmode { get; set; } = null;
    }
}