//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 5122ac90adfd
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Models.Components;
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class EntityCustomer
    {
        /// <summary>
        /// The full name of the customer.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; } = null;

        /// <summary>
        /// The email address of the customer.
        /// </summary>
        [JsonProperty("email")]
        public string? Email { get; set; } = null;

        /// <summary>
        /// Allows you to preset the language to be used.
        /// </summary>
        [JsonProperty("locale")]
        public LocaleResponse? Locale { get; set; } = null;

        /// <summary>
        /// Provide any data you like, for example a string or a JSON object. We will save the data alongside the entity. Whenever<br/>
        /// you fetch the entity with our API, we will also include the metadata. You can use up to approximately 1kB.
        /// </summary>
        [JsonProperty("metadata", NullValueHandling = NullValueHandling.Include)]
        public Metadata? Metadata { get; set; } = null;

        /// <summary>
        /// Whether to create the entity in test mode or live mode.<br/>
        /// <br/>
        /// Most API credentials are specifically created for either live mode or test mode, in which case this parameter must<br/>
        /// not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting<br/>
        /// `testmode` to `true`.
        /// </summary>
        [JsonProperty("testmode")]
        public bool? Testmode { get; set; } = null;
    }
}