//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 20ea22fd0bff
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;

    public enum LineCategories
    {
        [JsonProperty("eco")]
        Eco,
        [JsonProperty("gift")]
        Gift,
        [JsonProperty("meal")]
        Meal,
        [JsonProperty("sport_culture")]
        SportCulture,
        [JsonProperty("additional")]
        Additional,
        [JsonProperty("consume")]
        Consume,
    }

    public static class LineCategoriesExtension
    {
        public static string Value(this LineCategories value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static LineCategories ToEnum(this string value)
        {
            foreach(var field in typeof(LineCategories).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is LineCategories)
                    {
                        return (LineCategories)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum LineCategories");
        }
    }
}