//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: c2ae20908462
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// The amount deducted from your account balance for this refund, converted to the currency your account is<br/>
    /// settled in. Always a **negative** amount.<br/>
    /// <br/>
    /// For refunds not directly processed by Mollie (e.g. PayPal), the settlement amount is zero.
    /// </summary>
    public class ListSettlementRefundResponseSettlementAmount
    {
        /// <summary>
        /// A three-character ISO 4217 currency code.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; } = default!;

        /// <summary>
        /// A string containing an exact monetary amount in the given currency.
        /// </summary>
        [JsonProperty("value")]
        public string Value { get; set; } = default!;
    }
}