//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// The status of the mandate. A status can be `pending` for mandates when the first payment is not yet finalized, or<br/>
    /// 
    /// <remarks>
    /// when we did not received the IBAN yet from the first payment.
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class MandateStatus : IEquatable<MandateStatus>
    {
        public static readonly MandateStatus Valid = new MandateStatus("valid");
        public static readonly MandateStatus Pending = new MandateStatus("pending");
        public static readonly MandateStatus Invalid = new MandateStatus("invalid");

        private static readonly Dictionary <string, MandateStatus> _knownValues =
            new Dictionary <string, MandateStatus> ()
            {
                ["valid"] = Valid,
                ["pending"] = Pending,
                ["invalid"] = Invalid
            };

        private static readonly ConcurrentDictionary<string, MandateStatus> _values =
            new ConcurrentDictionary<string, MandateStatus>(_knownValues);

        private MandateStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static MandateStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new MandateStatus(value));
        }

        public static implicit operator MandateStatus(string value) => Of(value);
        public static implicit operator string(MandateStatus mandatestatus) => mandatestatus.Value;

        public static MandateStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as MandateStatus);

        public bool Equals(MandateStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}