//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// Normally, a payment method screen is shown. However, when using this parameter, you can choose a specific payment<br/>
    /// 
    /// <remarks>
    /// method and your customer will skip the selection screen and is sent directly to the chosen payment method. The<br/>
    /// parameter enables you to fully integrate the payment method selection into your website.<br/>
    /// <br/>
    /// You can also specify the methods in an array. By doing so we will still show the payment method selection screen<br/>
    /// but will only show the methods specified in the array. For example, you can use this functionality to only show<br/>
    /// payment methods from a specific country to your customer `[&apos;bancontact&apos;, &apos;belfius&apos;]`.
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class MethodResponse : IEquatable<MethodResponse>
    {
        public static readonly MethodResponse Alma = new MethodResponse("alma");
        public static readonly MethodResponse Applepay = new MethodResponse("applepay");
        public static readonly MethodResponse Bacs = new MethodResponse("bacs");
        public static readonly MethodResponse Bancomatpay = new MethodResponse("bancomatpay");
        public static readonly MethodResponse Bancontact = new MethodResponse("bancontact");
        public static readonly MethodResponse Banktransfer = new MethodResponse("banktransfer");
        public static readonly MethodResponse Belfius = new MethodResponse("belfius");
        public static readonly MethodResponse Billie = new MethodResponse("billie");
        public static readonly MethodResponse Bizum = new MethodResponse("bizum");
        public static readonly MethodResponse Blik = new MethodResponse("blik");
        public static readonly MethodResponse Creditcard = new MethodResponse("creditcard");
        public static readonly MethodResponse Directdebit = new MethodResponse("directdebit");
        public static readonly MethodResponse Eps = new MethodResponse("eps");
        public static readonly MethodResponse Giftcard = new MethodResponse("giftcard");
        public static readonly MethodResponse Ideal = new MethodResponse("ideal");
        public static readonly MethodResponse In3 = new MethodResponse("in3");
        public static readonly MethodResponse Kbc = new MethodResponse("kbc");
        public static readonly MethodResponse Klarna = new MethodResponse("klarna");
        public static readonly MethodResponse Mbway = new MethodResponse("mbway");
        public static readonly MethodResponse Mobilepay = new MethodResponse("mobilepay");
        public static readonly MethodResponse Multibanco = new MethodResponse("multibanco");
        public static readonly MethodResponse Mybank = new MethodResponse("mybank");
        public static readonly MethodResponse Paybybank = new MethodResponse("paybybank");
        public static readonly MethodResponse Payconiq = new MethodResponse("payconiq");
        public static readonly MethodResponse Paypal = new MethodResponse("paypal");
        public static readonly MethodResponse Paysafecard = new MethodResponse("paysafecard");
        public static readonly MethodResponse Pointofsale = new MethodResponse("pointofsale");
        public static readonly MethodResponse Przelewy24 = new MethodResponse("przelewy24");
        public static readonly MethodResponse Riverty = new MethodResponse("riverty");
        public static readonly MethodResponse Satispay = new MethodResponse("satispay");
        public static readonly MethodResponse Swish = new MethodResponse("swish");
        public static readonly MethodResponse Trustly = new MethodResponse("trustly");
        public static readonly MethodResponse Twint = new MethodResponse("twint");
        public static readonly MethodResponse Vipps = new MethodResponse("vipps");
        public static readonly MethodResponse Voucher = new MethodResponse("voucher");
        public static readonly MethodResponse Klarnapaylater = new MethodResponse("klarnapaylater");
        public static readonly MethodResponse Klarnapaynow = new MethodResponse("klarnapaynow");
        public static readonly MethodResponse Klarnasliceit = new MethodResponse("klarnasliceit");

        private static readonly Dictionary <string, MethodResponse> _knownValues =
            new Dictionary <string, MethodResponse> ()
            {
                ["alma"] = Alma,
                ["applepay"] = Applepay,
                ["bacs"] = Bacs,
                ["bancomatpay"] = Bancomatpay,
                ["bancontact"] = Bancontact,
                ["banktransfer"] = Banktransfer,
                ["belfius"] = Belfius,
                ["billie"] = Billie,
                ["bizum"] = Bizum,
                ["blik"] = Blik,
                ["creditcard"] = Creditcard,
                ["directdebit"] = Directdebit,
                ["eps"] = Eps,
                ["giftcard"] = Giftcard,
                ["ideal"] = Ideal,
                ["in3"] = In3,
                ["kbc"] = Kbc,
                ["klarna"] = Klarna,
                ["mbway"] = Mbway,
                ["mobilepay"] = Mobilepay,
                ["multibanco"] = Multibanco,
                ["mybank"] = Mybank,
                ["paybybank"] = Paybybank,
                ["payconiq"] = Payconiq,
                ["paypal"] = Paypal,
                ["paysafecard"] = Paysafecard,
                ["pointofsale"] = Pointofsale,
                ["przelewy24"] = Przelewy24,
                ["riverty"] = Riverty,
                ["satispay"] = Satispay,
                ["swish"] = Swish,
                ["trustly"] = Trustly,
                ["twint"] = Twint,
                ["vipps"] = Vipps,
                ["voucher"] = Voucher,
                ["klarnapaylater"] = Klarnapaylater,
                ["klarnapaynow"] = Klarnapaynow,
                ["klarnasliceit"] = Klarnasliceit
            };

        private static readonly ConcurrentDictionary<string, MethodResponse> _values =
            new ConcurrentDictionary<string, MethodResponse>(_knownValues);

        private MethodResponse(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static MethodResponse Of(string value)
        {
            return _values.GetOrAdd(value, _ => new MethodResponse(value));
        }

        public static implicit operator MethodResponse(string value) => Of(value);
        public static implicit operator string(MethodResponse methodresponse) => methodresponse.Value;

        public static MethodResponse[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as MethodResponse);

        public bool Equals(MethodResponse? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }

}