//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// **Netherlands legal entities types.**<br/>
    /// <br/>
    ///   * `nl-bv` - Besloten Vennootschap (BV)<br/>
    ///   * `nl-cooperatie` - Coöperatie<br/>
    ///   * `nl-cv` - Commanditaire Vennootschap (CV)<br/>
    ///   * `nl-eenmanszaak` - Eenmanszaak<br/>
    ///   * `nl-eesv` - Europees Economisch Samenwerkingsverband (EESV)<br/>
    ///   * `nl-kerkgenootschap` - Kerkgenootschap<br/>
    ///   * `nl-kroondomein` - Kroondomein<br/>
    ///   * `nl-maatschap` - Maatschap<br/>
    ///   * `nl-nv` - Naamloze Vennootschap (NV)<br/>
    ///   * `nl-overheid` - Overheidsinstantie<br/>
    ///   * `nl-sce` - Europese Coöperatieve Vennootschap (SCE)<br/>
    ///   * `nl-se` - Europese Naamloze Vennootschap (SE)<br/>
    ///   * `nl-stichting` - Stichting<br/>
    ///   * `nl-trust` - Trust<br/>
    ///   * `nl-vereniging` - Vereniging<br/>
    ///   * `nl-vof` - Vennootschap Onder Firma (VOF)<br/>
    ///   * `nl-waarborgmaatschappij` - Onderlinge Waarborgmaatschappij.
    /// </summary>
    public enum Nl
    {
        [JsonProperty("nl-bv")]
        NlBv,
        [JsonProperty("nl-cooperatie")]
        NlCooperatie,
        [JsonProperty("nl-cv")]
        NlCv,
        [JsonProperty("nl-eenmanszaak")]
        NlEenmanszaak,
        [JsonProperty("nl-eesv")]
        NlEesv,
        [JsonProperty("nl-kerkgenootschap")]
        NlKerkgenootschap,
        [JsonProperty("nl-kroondomein")]
        NlKroondomein,
        [JsonProperty("nl-maatschap")]
        NlMaatschap,
        [JsonProperty("nl-nv")]
        NlNv,
        [JsonProperty("nl-overheid")]
        NlOverheid,
        [JsonProperty("nl-sce")]
        NlSce,
        [JsonProperty("nl-se")]
        NlSe,
        [JsonProperty("nl-stichting")]
        NlStichting,
        [JsonProperty("nl-trust")]
        NlTrust,
        [JsonProperty("nl-vereniging")]
        NlVereniging,
        [JsonProperty("nl-vof")]
        NlVof,
        [JsonProperty("nl-waarborgmaatschappij")]
        NlWaarborgmaatschappij,
    }

    public static class NlExtension
    {
        public static string Value(this Nl value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Nl ToEnum(this string value)
        {
            foreach(var field in typeof(Nl).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Nl)
                    {
                        return (Nl)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Nl");
        }
    }
}