//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 5982adab4a1e
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The applicable card fee region.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class PaymentDetailsFeeRegionResponse : IEquatable<PaymentDetailsFeeRegionResponse>, IOpenEnum<string>
    {
        public static readonly PaymentDetailsFeeRegionResponse AmericanExpress = new PaymentDetailsFeeRegionResponse("american-express");
        public static readonly PaymentDetailsFeeRegionResponse AmexIntraEea = new PaymentDetailsFeeRegionResponse("amex-intra-eea");
        public static readonly PaymentDetailsFeeRegionResponse CarteBancaire = new PaymentDetailsFeeRegionResponse("carte-bancaire");
        public static readonly PaymentDetailsFeeRegionResponse CartesBancairesBusiness = new PaymentDetailsFeeRegionResponse("cartes-bancaires-business");
        public static readonly PaymentDetailsFeeRegionResponse CartesBancairesConsumer = new PaymentDetailsFeeRegionResponse("cartes-bancaires-consumer");
        public static readonly PaymentDetailsFeeRegionResponse Domestic = new PaymentDetailsFeeRegionResponse("domestic");
        public static readonly PaymentDetailsFeeRegionResponse Inter = new PaymentDetailsFeeRegionResponse("inter");
        public static readonly PaymentDetailsFeeRegionResponse IntraEu = new PaymentDetailsFeeRegionResponse("intra-eu");
        public static readonly PaymentDetailsFeeRegionResponse IntraEuCorporate = new PaymentDetailsFeeRegionResponse("intra-eu-corporate");
        public static readonly PaymentDetailsFeeRegionResponse IntraEea = new PaymentDetailsFeeRegionResponse("intra_eea");
        public static readonly PaymentDetailsFeeRegionResponse Maestro = new PaymentDetailsFeeRegionResponse("maestro");
        public static readonly PaymentDetailsFeeRegionResponse MastercardCreditBusinessDomestic = new PaymentDetailsFeeRegionResponse("mastercard-credit-business-domestic");
        public static readonly PaymentDetailsFeeRegionResponse MastercardCreditConsumerDomestic = new PaymentDetailsFeeRegionResponse("mastercard-credit-consumer-domestic");
        public static readonly PaymentDetailsFeeRegionResponse MastercardCreditConsumerIntraEea = new PaymentDetailsFeeRegionResponse("mastercard-credit-consumer-intra-eea");
        public static readonly PaymentDetailsFeeRegionResponse MastercardDebitBusinessDomestic = new PaymentDetailsFeeRegionResponse("mastercard-debit-business-domestic");
        public static readonly PaymentDetailsFeeRegionResponse MastercardDebitBusinessIntraEea = new PaymentDetailsFeeRegionResponse("mastercard-debit-business-intra-eea");
        public static readonly PaymentDetailsFeeRegionResponse MastercardDebitConsumerDomestic = new PaymentDetailsFeeRegionResponse("mastercard-debit-consumer-domestic");
        public static readonly PaymentDetailsFeeRegionResponse MastercardDebitConsumerInter = new PaymentDetailsFeeRegionResponse("mastercard-debit-consumer-inter");
        public static readonly PaymentDetailsFeeRegionResponse MastercardDebitConsumerIntraEea = new PaymentDetailsFeeRegionResponse("mastercard-debit-consumer-intra-eea");
        public static readonly PaymentDetailsFeeRegionResponse Other = new PaymentDetailsFeeRegionResponse("other");
        public static readonly PaymentDetailsFeeRegionResponse VisaCreditBusinessDomestic = new PaymentDetailsFeeRegionResponse("visa-credit-business-domestic");
        public static readonly PaymentDetailsFeeRegionResponse VisaCreditConsumerDomestic = new PaymentDetailsFeeRegionResponse("visa-credit-consumer-domestic");
        public static readonly PaymentDetailsFeeRegionResponse VisaCreditConsumerInter = new PaymentDetailsFeeRegionResponse("visa-credit-consumer-inter");
        public static readonly PaymentDetailsFeeRegionResponse VisaCreditConsumerIntraEea = new PaymentDetailsFeeRegionResponse("visa-credit-consumer-intra-eea");
        public static readonly PaymentDetailsFeeRegionResponse VisaDebitBusinessDomestic = new PaymentDetailsFeeRegionResponse("visa-debit-business-domestic");
        public static readonly PaymentDetailsFeeRegionResponse VisaDebitBusinessIntraEea = new PaymentDetailsFeeRegionResponse("visa-debit-business-intra-eea");
        public static readonly PaymentDetailsFeeRegionResponse VisaDebitConsumerDomestic = new PaymentDetailsFeeRegionResponse("visa-debit-consumer-domestic");
        public static readonly PaymentDetailsFeeRegionResponse VisaDebitConsumerInter = new PaymentDetailsFeeRegionResponse("visa-debit-consumer-inter");
        public static readonly PaymentDetailsFeeRegionResponse VisaDebitConsumerIntraEea = new PaymentDetailsFeeRegionResponse("visa-debit-consumer-intra-eea");

        private static readonly Dictionary <string, PaymentDetailsFeeRegionResponse> _knownValues =
            new Dictionary <string, PaymentDetailsFeeRegionResponse> ()
            {
                ["american-express"] = AmericanExpress,
                ["amex-intra-eea"] = AmexIntraEea,
                ["carte-bancaire"] = CarteBancaire,
                ["cartes-bancaires-business"] = CartesBancairesBusiness,
                ["cartes-bancaires-consumer"] = CartesBancairesConsumer,
                ["domestic"] = Domestic,
                ["inter"] = Inter,
                ["intra-eu"] = IntraEu,
                ["intra-eu-corporate"] = IntraEuCorporate,
                ["intra_eea"] = IntraEea,
                ["maestro"] = Maestro,
                ["mastercard-credit-business-domestic"] = MastercardCreditBusinessDomestic,
                ["mastercard-credit-consumer-domestic"] = MastercardCreditConsumerDomestic,
                ["mastercard-credit-consumer-intra-eea"] = MastercardCreditConsumerIntraEea,
                ["mastercard-debit-business-domestic"] = MastercardDebitBusinessDomestic,
                ["mastercard-debit-business-intra-eea"] = MastercardDebitBusinessIntraEea,
                ["mastercard-debit-consumer-domestic"] = MastercardDebitConsumerDomestic,
                ["mastercard-debit-consumer-inter"] = MastercardDebitConsumerInter,
                ["mastercard-debit-consumer-intra-eea"] = MastercardDebitConsumerIntraEea,
                ["other"] = Other,
                ["visa-credit-business-domestic"] = VisaCreditBusinessDomestic,
                ["visa-credit-consumer-domestic"] = VisaCreditConsumerDomestic,
                ["visa-credit-consumer-inter"] = VisaCreditConsumerInter,
                ["visa-credit-consumer-intra-eea"] = VisaCreditConsumerIntraEea,
                ["visa-debit-business-domestic"] = VisaDebitBusinessDomestic,
                ["visa-debit-business-intra-eea"] = VisaDebitBusinessIntraEea,
                ["visa-debit-consumer-domestic"] = VisaDebitConsumerDomestic,
                ["visa-debit-consumer-inter"] = VisaDebitConsumerInter,
                ["visa-debit-consumer-intra-eea"] = VisaDebitConsumerIntraEea
            };

        private static readonly ConcurrentDictionary<string, PaymentDetailsFeeRegionResponse> _values =
            new ConcurrentDictionary<string, PaymentDetailsFeeRegionResponse>(_knownValues);

        private PaymentDetailsFeeRegionResponse(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static PaymentDetailsFeeRegionResponse Of(string value)
        {
            return _values.GetOrAdd(value, _ => new PaymentDetailsFeeRegionResponse(value));
        }

        public static implicit operator PaymentDetailsFeeRegionResponse(string value) => Of(value);
        public static implicit operator string(PaymentDetailsFeeRegionResponse paymentdetailsfeeregionresponse) => paymentdetailsfeeregionresponse.Value;

        public static PaymentDetailsFeeRegionResponse[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as PaymentDetailsFeeRegionResponse);

        public bool Equals(PaymentDetailsFeeRegionResponse? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}