//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: b8f08c743e32
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Models.Components;
    using Mollie.Utils;
    using Newtonsoft.Json;
    using NodaTime;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// An object containing payment details collected during the payment process. For example, details may include the<br/>
    /// customer's card or bank details and a payment reference. For the full list of details, please refer to the<br/>
    /// <a href="extra-payment-parameters">method-specific parameters</a> guide.
    /// </summary>
    public class PaymentResponseDetails
    {
        /// <summary>
        /// The customer's name, if made available by the payment method. For card payments, refer to details.cardHolder.
        /// </summary>
        [JsonProperty("consumerName")]
        public string? ConsumerName { get; set; } = null;

        /// <summary>
        /// The customer's account reference.<br/>
        /// <br/>
        /// For banking-based payment methods — such as iDEAL — this is normally either an IBAN or a domestic bank account<br/>
        /// number.<br/>
        /// <br/>
        /// For PayPal, the account reference is an email address.<br/>
        /// <br/>
        /// For card and Bancontact payments, refer to details.cardNumber.
        /// </summary>
        [JsonProperty("consumerAccount")]
        public string? ConsumerAccount { get; set; } = null;

        /// <summary>
        /// The BIC of the customer's bank account, if applicable.
        /// </summary>
        [JsonProperty("consumerBic")]
        public string? ConsumerBic { get; set; } = null;

        /// <summary>
        /// For wallet payment methods — such as Apple Pay and PayPal — the shipping address is often already known by the<br/>
        /// wallet provider. In these cases the shipping address may be available as a payment detail.
        /// </summary>
        [JsonProperty("shippingAddress")]
        public Dictionary<string, object>? ShippingAddress { get; set; } = null;

        /// <summary>
        /// For bancontact, it will be the customer's masked card number. For cards, it will be the last 4-digit of the<br/>
        /// PAN. For Point-of-sale, it will be the the last 4 digits of the customer's masked card number.
        /// </summary>
        [JsonProperty("cardNumber")]
        public string? CardNumber { get; set; } = null;

        /// <summary>
        /// The name of the bank that the customer will need to make the bank transfer payment towards.
        /// </summary>
        [JsonProperty("bankName")]
        public string? BankName { get; set; }

        /// <summary>
        /// The bank account number the customer will need to make the bank transfer payment towards.
        /// </summary>
        [JsonProperty("bankAccount")]
        public string? BankAccount { get; set; }

        /// <summary>
        /// The BIC of the bank the customer will need to make the bank transfer payment towards.
        /// </summary>
        [JsonProperty("bankBic")]
        public string? BankBic { get; set; }

        /// <summary>
        /// The Mollie-generated reference the customer needs to use when transfering the amount. Do not apply any<br/>
        /// formatting here; show it to the customer as-is.
        /// </summary>
        [JsonProperty("transferReference")]
        public string? TransferReference { get; set; } = null;

        /// <summary>
        /// A unique fingerprint for a specific card. Can be used to identify returning customers.<br/>
        /// <br/>
        /// In the case of Point-of-sale payments, it's a unique identifier assigned to a cardholder's payment account,<br/>
        /// linking multiple transactions from wallets and physical card to a single account, also across payment methods<br/>
        /// or when the card is reissued.
        /// </summary>
        [JsonProperty("cardFingerprint")]
        public string? CardFingerprint { get; set; } = null;

        /// <summary>
        /// The customer's name as shown on their card.
        /// </summary>
        [JsonProperty("cardHolder")]
        public string? CardHolder { get; set; } = null;

        /// <summary>
        /// The card's target audience, if known.
        /// </summary>
        [JsonProperty("cardAudition")]
        public PaymentDetailsCardAuditionResponse? CardAudition { get; set; } = null;

        /// <summary>
        /// The card's label, if known.
        /// </summary>
        [JsonProperty("cardLabel")]
        public PaymentDetailsCardLabelResponse? CardLabel { get; set; } = null;

        /// <summary>
        /// The ISO 3166-1 alpha-2 country code of the country the card was issued in.
        /// </summary>
        [JsonProperty("cardCountryCode")]
        public string? CardCountryCode { get; set; } = null;

        /// <summary>
        /// The expiry date (MM/YY) of the card as displayed on the card.
        /// </summary>
        [JsonProperty("cardExpiryDate")]
        public string? CardExpiryDate { get; set; } = null;

        /// <summary>
        /// The card type.
        /// </summary>
        [JsonProperty("cardFunding")]
        public PaymentDetailsCardFundingResponse? CardFunding { get; set; } = null;

        /// <summary>
        /// The level of security applied during card processing.
        /// </summary>
        [JsonProperty("cardSecurity")]
        public PaymentDetailsCardSecurityResponse? CardSecurity { get; set; } = null;

        /// <summary>
        /// The applicable card fee region.
        /// </summary>
        [JsonProperty("feeRegion")]
        public PaymentDetailsFeeRegionResponse? FeeRegion { get; set; } = null;

        /// <summary>
        /// The first 6 and last 4 digits of the card number.
        /// </summary>
        [JsonProperty("cardMaskedNumber")]
        public string? CardMaskedNumber { get; set; } = null;

        /// <summary>
        /// The outcome of authentication attempted on transactions enforced by 3DS (ie valid only for oneoff and first).
        /// </summary>
        [JsonProperty("card3dsEci")]
        public string? Card3dsEci { get; set; } = null;

        /// <summary>
        /// The first 6 digit of the card bank identification number.
        /// </summary>
        [JsonProperty("cardBin")]
        public string? CardBin { get; set; } = null;

        /// <summary>
        /// The issuer of the Card.
        /// </summary>
        [JsonProperty("cardIssuer")]
        public string? CardIssuer { get; set; } = null;

        /// <summary>
        /// A failure code to help understand why the payment failed.
        /// </summary>
        [JsonProperty("failureReason")]
        public PaymentDetailsFailureReasonResponse? FailureReason { get; set; } = null;

        /// <summary>
        /// A human-friendly failure message that can be shown to the customer. The message is translated in accordance<br/>
        /// with the payment's locale setting.
        /// </summary>
        [JsonProperty("failureMessage")]
        public string? FailureMessage { get; set; } = null;

        /// <summary>
        /// The wallet used when creating the payment.
        /// </summary>
        [JsonProperty("wallet")]
        public PaymentDetailsWalletResponse? Wallet { get; set; } = null;

        /// <summary>
        /// PayPal's reference for the payment.
        /// </summary>
        [JsonProperty("paypalReference")]
        public string? PaypalReference { get; set; } = null;

        /// <summary>
        /// ID of the customer's PayPal account.
        /// </summary>
        [JsonProperty("paypalPayerId")]
        public string? PaypalPayerId { get; set; } = null;

        /// <summary>
        /// Indicates to what extent the payment is eligible for PayPal's Seller Protection. Only available for PayPal<br/>
        /// payments, and if the information is made available by PayPal.
        /// </summary>
        [JsonProperty("sellerProtection")]
        public PaymentDetailsSellerProtectionResponse? SellerProtection { get; set; } = null;

        /// <summary>
        /// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
        /// </summary>
        [JsonProperty("paypalFee")]
        public AmountNullable? PaypalFee { get; set; } = null;

        /// <summary>
        /// The paysafecard customer reference either provided via the API or otherwise auto-generated by Mollie.
        /// </summary>
        [JsonProperty("customerReference")]
        public string? CustomerReference { get; set; }

        /// <summary>
        /// The ID of the terminal device where the payment took place on.
        /// </summary>
        [JsonProperty("terminalId")]
        public string? TerminalId { get; set; }

        /// <summary>
        /// The first 6 digits &amp; last 4 digits of the customer's masked card number.
        /// </summary>
        [JsonProperty("maskedNumber")]
        public string? MaskedNumber { get; set; } = null;

        /// <summary>
        /// The Point of sale receipt object.
        /// </summary>
        [JsonProperty("receipt")]
        public PaymentResponseReceipt? Receipt { get; set; }

        /// <summary>
        /// The creditor identifier indicates who is authorized to execute the payment. In this case, it is a<br/>
        /// reference to Mollie.
        /// </summary>
        [JsonProperty("creditorIdentifier")]
        public string? CreditorIdentifier { get; set; } = null;

        /// <summary>
        /// Estimated date the payment is debited from the customer's bank account, in YYYY-MM-DD format.
        /// </summary>
        [JsonProperty("dueDate")]
        public LocalDate? DueDate { get; set; } = null;

        /// <summary>
        /// Date the payment has been signed by the customer, in YYYY-MM-DD format. Only available if the payment<br/>
        /// has been signed.
        /// </summary>
        [JsonProperty("signatureDate")]
        public LocalDate? SignatureDate { get; set; } = null;

        /// <summary>
        /// The official reason why this payment has failed. A detailed description of each reason is available on the<br/>
        /// website of the European Payments Council.
        /// </summary>
        [JsonProperty("bankReasonCode")]
        public string? BankReasonCode { get; set; } = null;

        /// <summary>
        /// A human-friendly description of the failure reason.
        /// </summary>
        [JsonProperty("bankReason")]
        public string? BankReason { get; set; } = null;

        /// <summary>
        /// The end-to-end identifier you provided in the batch file.
        /// </summary>
        [JsonProperty("endToEndIdentifier")]
        public string? EndToEndIdentifier { get; set; } = null;

        /// <summary>
        /// The mandate reference you provided in the batch file.
        /// </summary>
        [JsonProperty("mandateReference")]
        public string? MandateReference { get; set; } = null;

        /// <summary>
        /// The batch reference you provided in the batch file.
        /// </summary>
        [JsonProperty("batchReference")]
        public string? BatchReference { get; set; } = null;

        /// <summary>
        /// The file reference you provided in the batch file.
        /// </summary>
        [JsonProperty("fileReference")]
        public string? FileReference { get; set; } = null;

        /// <summary>
        /// Optional include. If a QR code was requested during payment creation for a QR-compatible payment method,<br/>
        /// the QR code details will be available in this object.<br/>
        /// <br/>
        /// The QR code can be scanned by the customer to complete the payment on their mobile device. For example,<br/>
        /// Bancontact QR payments can be completed by the customer using the Bancontact app.
        /// </summary>
        [JsonProperty("qrCode")]
        public PaymentResponseQrCode? QrCode { get; set; }

        /// <summary>
        /// For payments with gift cards: the masked gift card number of the first gift card applied to the payment.
        /// </summary>
        [JsonProperty("voucherNumber")]
        public string? VoucherNumber { get; set; }

        /// <summary>
        /// An array of detail objects for each gift card that was used on this payment, if any.
        /// </summary>
        [JsonProperty("giftcards")]
        public List<Dictionary<string, object>>? Giftcards { get; set; }

        /// <summary>
        /// For payments with vouchers: the brand name of the first voucher applied.
        /// </summary>
        [JsonProperty("issuer")]
        public string? Issuer { get; set; }

        /// <summary>
        /// An array of detail objects for each voucher that was used on this payment, if any.
        /// </summary>
        [JsonProperty("vouchers")]
        public List<Dictionary<string, object>>? Vouchers { get; set; }

        /// <summary>
        /// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
        /// </summary>
        [JsonProperty("remainderAmount")]
        public Amount? RemainderAmount { get; set; }

        /// <summary>
        /// The payment method used to pay the remainder amount, after all gift cards or vouchers were applied.
        /// </summary>
        [JsonProperty("remainderMethod")]
        public string? RemainderMethod { get; set; }

        /// <summary>
        /// Optional include. The full payment method details of the remainder payment.
        /// </summary>
        [JsonProperty("remainderDetails")]
        public Dictionary<string, object>? RemainderDetails { get; set; }

        /// <summary>
        /// Multibanco payment reference of the transaction.
        /// </summary>
        [JsonProperty("multibancoReference")]
        public string? MultibancoReference { get; set; } = null;

        /// <summary>
        /// Multibanco entity reference of the transaction.
        /// </summary>
        [JsonProperty("multibancoEntity")]
        public string? MultibancoEntity { get; set; } = null;
    }
}