//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The type of source. Currently only the source type `organization` is supported.
    /// </summary>
    public enum RoutingReversalType
    {
        [JsonProperty("organization")]
        Organization,
    }

    public static class RoutingReversalTypeExtension
    {
        public static string Value(this RoutingReversalType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static RoutingReversalType ToEnum(this string value)
        {
            foreach(var field in typeof(RoutingReversalType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is RoutingReversalType)
                    {
                        return (RoutingReversalType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum RoutingReversalType");
        }
    }

}