//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 697bc2ae0e65
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The status for the invoice to end up in.<br/>
    /// <br/>
    /// A `draft` invoice is not paid or not sent and can be updated after creation. Setting it to `issued` sends it to<br/>
    /// the recipient so they may then pay through our payment system. To skip our payment process, set this to `paid` to<br/>
    /// mark it as paid. It can then subsequently be sent as well, same as with `issued`.<br/>
    /// <br/>
    /// Dependent parameters:<br/>
    ///   - `paymentDetails` is required if invoice should be set directly to `paid`<br/>
    ///   - `customerId` and `mandateId` are required if a recurring payment should be used to set the invoice to `paid`<br/>
    ///   - `emailDetails` optional for `issued` and `paid` to send the invoice by email.
    /// </summary>
    public enum SalesInvoiceStatusUpdate
    {
        [JsonProperty("draft")]
        Draft,
        [JsonProperty("issued")]
        Issued,
        [JsonProperty("paid")]
        Paid,
        [JsonProperty("cancelled")]
        Cancelled,
    }

    public static class SalesInvoiceStatusUpdateExtension
    {
        public static string Value(this SalesInvoiceStatusUpdate value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static SalesInvoiceStatusUpdate ToEnum(this string value)
        {
            foreach(var field in typeof(SalesInvoiceStatusUpdate).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is SalesInvoiceStatusUpdate)
                    {
                        return (SalesInvoiceStatusUpdate)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum SalesInvoiceStatusUpdate");
        }
    }
}