//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// **Sweden legal entities types.**<br/>
    /// <br/>
    ///   * `se-ab` - Aktiebolag (AB)<br/>
    ///   * `se-ab-publ` - AB (publ)<br/>
    ///   * `se-ekonomisk-forening` - Ekonomisk förening<br/>
    ///   * `se-enkla-bolag` - Enkla bolag<br/>
    ///   * `se-enskild-firma` - Enskild firma<br/>
    ///   * `se-fillial-utlandskt-bolag` - Fillial till utländskt bolag<br/>
    ///   * `se-hb` - Handelsbolag (HB)<br/>
    ///   * `se-ideel-forening` - Ideel förening<br/>
    ///   * `se-kb` - Kommanditbolag (KB)<br/>
    ///   * `se-samriskforetag` - Samriskföretag<br/>
    ///   * `se-stiftelse` - Stiftelse<br/>
    ///   * `se-trust` - Trust.
    /// </summary>
    public enum Se
    {
        [JsonProperty("se-ab")]
        SeAb,
        [JsonProperty("se-ab-publ")]
        SeAbPubl,
        [JsonProperty("se-ekonomisk-forening")]
        SeEkonomiskForening,
        [JsonProperty("se-enkla-bolag")]
        SeEnklaBolag,
        [JsonProperty("se-enskild-firma")]
        SeEnskildFirma,
        [JsonProperty("se-fillial-utlandskt-bolag")]
        SeFillialUtlandsktBolag,
        [JsonProperty("se-hb")]
        SeHb,
        [JsonProperty("se-ideel-forening")]
        SeIdeelForening,
        [JsonProperty("se-kb")]
        SeKb,
        [JsonProperty("se-samriskforetag")]
        SeSamriskforetag,
        [JsonProperty("se-stiftelse")]
        SeStiftelse,
        [JsonProperty("se-trust")]
        SeTrust,
    }

    public static class SeExtension
    {
        public static string Value(this Se value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Se ToEnum(this string value)
        {
            foreach(var field in typeof(Se).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Se)
                    {
                        return (Se)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Se");
        }
    }
}