//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 5d9652257aae
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Models.Components;
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The scheme, as requested by the client.
    /// </summary>
    public class TransferSchemeResponse
    {
        /// <summary>
        /// The transfer scheme to be used for the transfer. The transfer scheme determines the processing time and method of the transfer.
        /// </summary>
        [JsonProperty("type")]
        public TransferSchemeTypeResponse Type { get; set; } = default!;
    }
}