//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: ab5998e4c36a
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Mollie.Models.Components
{
    using Mollie.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The current status of the action.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class UnmatchedCreditTransferActionResponseStatus : IEquatable<UnmatchedCreditTransferActionResponseStatus>
    {
        public static readonly UnmatchedCreditTransferActionResponseStatus Pending = new UnmatchedCreditTransferActionResponseStatus("pending");

        private static readonly Dictionary <string, UnmatchedCreditTransferActionResponseStatus> _knownValues =
            new Dictionary <string, UnmatchedCreditTransferActionResponseStatus> ()
            {
                ["pending"] = Pending
            };

        private static readonly ConcurrentDictionary<string, UnmatchedCreditTransferActionResponseStatus> _values =
            new ConcurrentDictionary<string, UnmatchedCreditTransferActionResponseStatus>(_knownValues);

        private UnmatchedCreditTransferActionResponseStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static UnmatchedCreditTransferActionResponseStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new UnmatchedCreditTransferActionResponseStatus(value));
        }

        public static implicit operator UnmatchedCreditTransferActionResponseStatus(string value) => Of(value);
        public static implicit operator string(UnmatchedCreditTransferActionResponseStatus unmatchedcredittransferactionresponsestatus) => unmatchedcredittransferactionresponsestatus.Value;

        public static UnmatchedCreditTransferActionResponseStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as UnmatchedCreditTransferActionResponseStatus);

        public bool Equals(UnmatchedCreditTransferActionResponseStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}